name: nightcore

networks:
  nightcore-network:
    name: nightcore-network
    driver: bridge

services:
  nightcore-bot:
    image: nightcore-bot:latest
    container_name: nightcore-bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    env_file:
      - .env

    ports:
      - "${BOT_PORT}:${BOT_PORT}"

    volumes:
      - ./src/:/app/src/
      - ./main.py:/app/main.py
      - ./alembic.ini:/app/alembic.ini
      - ./migrations/:/app/migrations/
    networks:
      - nightcore-network

    depends_on:
      nightcore-db:
        condition: service_healthy

  nightcore-db:
    image: postgres:16-alpine
    container_name: nightcore-db
    restart: no
    env_file:
      - .env

    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=nightcore --dbname=nightcore"]
      interval: 5s
      timeout: 3s
      retries: 5

    networks:
      - nightcore-network