name: nightcore

networks:
  nightcore-network:
    name: nightcore-network
    driver: bridge

services:
  nightcore-bot:
    image: nightcore-bot:latest
    container_name: nightcore-bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    env_file:
      - .env

    volumes:
      - ./src/:/app/src/
      - ./main.py:/app/main.py
      - ./alembic.ini:/app/alembic.ini
      - ./migrations/:/app/migrations/
    networks:
      - nightcore-network

    depends_on:
      nightcore-db:
        condition: service_healthy
      nightcore-redis:
        condition: service_healthy

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard-backend.rule=Host(`${API_DOMAIN}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.dashboard-backend.priority=10"
      - "traefik.http.routers.dashboard-backend.entrypoints=web"
      - "traefik.http.routers.dashboard-backend.service=dashboard-backend"
      - "traefik.http.services.dashboard-backend.loadbalancer.server.port=${API_PORT}"
      - "traefik.http.routers.dashboard-backend.tls=false"

  nightcore-db:
    image: postgres:16-alpine
    container_name: nightcore-db
    restart: no
    env_file:
      - .env

    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --username=nightcore --dbname=nightcore" ]
      interval: 5s
      timeout: 3s
      retries: 5

    networks:
      - nightcore-network

  traefik:
    image: traefik:v3.7.1
    container_name: nightcore-traefik
    restart: unless-stopped
    command:
      - --api.dashboard=true
      - --api.insecure=true

      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=nightcore-network

      - --entrypoints.web.address=:80

      - --log.level=INFO
      - --accesslog=true
      - --accesslog.format=json

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme.json:/acme.json

    networks:
      - nightcore-network