"""add customcomponent model

Revision ID: 03059ad0efa7
Revises: f19803671fa4
Create Date: 2025-12-20 21:49:16.126066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03059ad0efa7'
down_revision: Union[str, Sequence[str], None] = 'f19803671fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customcomponent',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('moderator_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('embed', 'v2_component', name='componenttypeenum', native_enum=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('author_text', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_changestats_guild_id_name', 'customcomponent', ['guild_id', 'name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_changestats_guild_id_name', table_name='customcomponent')
    op.drop_table('customcomponent')
    # ### end Alembic commands ###
