"""add_voteban_state

Revision ID: 16ce54fc6920
Revises: 75925089facf
Create Date: 2026-05-03 20:59:51.492122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16ce54fc6920'
down_revision: Union[str, Sequence[str], None] = '75925089facf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votebanstate',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('moderator_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('original_duration', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('original_delete_messages_per', sa.String(), nullable=True),
    sa.Column('delete_messages_per', sa.Integer(), nullable=True),
    sa.Column('against_moderators_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('for_moderators_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('attachments_urls', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('state', sa.Enum('pending', 'approved', 'denied', name='votebanstateenum', native_enum=False), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vote_ban_guild_user_state', 'votebanstate', ['guild_id', 'user_id', 'state'], unique=False)
    op.create_index('uq_vote_ban_guild_user_pending', 'votebanstate', ['guild_id', 'user_id'], unique=True, postgresql_where=sa.text("state = 'pending'"))
    op.drop_constraint(op.f('uq_guild_channel_role_section'), 'guildforumconfig', type_='unique')
    op.create_unique_constraint(None, 'guildforumconfig', ['section_id'])
    op.create_unique_constraint(None, 'guildforumconfig', ['role_id'])
    op.create_unique_constraint(None, 'guildforumconfig', ['guild_id'])
    op.create_unique_constraint(None, 'guildforumconfig', ['channel_id'])
    op.create_unique_constraint(None, 'processedforumthread', ['thread_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'processedforumthread', type_='unique')
    op.drop_constraint(None, 'guildforumconfig', type_='unique')
    op.drop_constraint(None, 'guildforumconfig', type_='unique')
    op.drop_constraint(None, 'guildforumconfig', type_='unique')
    op.drop_constraint(None, 'guildforumconfig', type_='unique')
    op.create_unique_constraint(op.f('uq_guild_channel_role_section'), 'guildforumconfig', ['guild_id', 'channel_id', 'role_id', 'section_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('uq_vote_ban_guild_user_pending', table_name='votebanstate', postgresql_where=sa.text("state = 'pending'"))
    op.drop_index('idx_vote_ban_guild_user_state', table_name='votebanstate')
    op.drop_table('votebanstate')
    # ### end Alembic commands ###
