"""Thu Aug 21 10:18:23 PM CEST 2025

Revision ID: 17a45cbbbb6b
Revises: 2157f7262dd0
Create Date: 2025-08-21 22:18:28.081942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17a45cbbbb6b'
down_revision: Union[str, Sequence[str], None] = '2157f7262dd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # duration: VARCHAR -> INTEGER
    op.alter_column(
        'punish',
        'duration',
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=True,
        postgresql_using="NULLIF(duration, '')::integer"
    )

    # end_time: INTEGER (epoch seconds) -> TIMESTAMP WITH TIME ZONE
    op.alter_column(
        'punish',
        'end_time',
        existing_type=sa.INTEGER(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        postgresql_using="to_timestamp(end_time)"
    )

    # time_now: INTEGER (epoch seconds) -> TIMESTAMP WITH TIME ZONE
    op.alter_column(
        'punish',
        'time_now',
        existing_type=sa.INTEGER(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        postgresql_using="to_timestamp(time_now)"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('punish', 'time_now',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('punish', 'end_time',
               existing_type=sa.DateTime(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('punish', 'duration',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
