"""Revision (Fri Aug 28 20:58:44 CEST 2026)

Revision ID: 1d2e7e87b339
Revises: d44bc132697a
Create Date: 2026-08-28 20:58:45.544663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d2e7e87b339'
down_revision: Union[str, Sequence[str], None] = 'd44bc132697a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guildbonusrole', sa.Column('exp', sa.Integer(), nullable=False))
    op.add_column('guildbonusrole', sa.Column('battlepass_points', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guildbonusrole', 'battlepass_points')
    op.drop_column('guildbonusrole', 'exp')
    # ### end Alembic commands ###
