"""Mon Oct 20 08:34:57 PM CEST 2025

Revision ID: 1f8941859ed8
Revises: b1cbe8459b83
Create Date: 2025-10-20 20:34:59.446626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f8941859ed8'
down_revision: Union[str, Sequence[str], None] = 'b1cbe8459b83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clanmember_user_ref_id'), table_name='clanmember')
    op.drop_constraint(op.f('clanmember_user_ref_id_fkey'), 'clanmember', type_='foreignkey')
    op.drop_column('clanmember', 'user_ref_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clanmember', sa.Column('user_ref_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('clanmember_user_ref_id_fkey'), 'clanmember', 'user', ['user_ref_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_clanmember_user_ref_id'), 'clanmember', ['user_ref_id'], unique=True)
    # ### end Alembic commands ###
