"""Tue Aug 19 09:58:03 PM CEST 2025

Revision ID: 2157f7262dd0
Revises: 
Create Date: 2025-08-19 21:58:08.489221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2157f7262dd0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clan',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('leader_id', sa.BigInteger(), nullable=False),
    sa.Column('deputies', sa.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('coins', sa.Float(), nullable=False),
    sa.Column('current_exp', sa.BigInteger(), nullable=False),
    sa.Column('exp_to_level', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.BigInteger(), nullable=False),
    sa.Column('max_deputies', sa.Integer(), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('payday_multipler', sa.Integer(), nullable=False),
    sa.Column('invite_message', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guildclansconfig',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('clan_payday_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('clan_shop_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('clan_shop_products', sa.JSON(), nullable=False),
    sa.Column('clan_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('create_clan_role_id', sa.BigInteger(), nullable=True),
    sa.Column('clan_buy_ping_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('clan_reputation', sa.Float(), nullable=False),
    sa.Column('clan_improvements', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_table('guildeconomyconfig',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('coin_name', sa.String(), nullable=True),
    sa.Column('economy_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('reward_bonus', sa.Float(), nullable=True),
    sa.Column('economy_shop_buy_ping_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('economy_shop', sa.JSON(), nullable=False),
    sa.Column('economy_products', sa.JSON(), nullable=False),
    sa.Column('colors', sa.JSON(), nullable=False),
    sa.Column('drop_from_cases', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_table('guildlevelsconfig',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('count_messages_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('level_notify_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('base_exp_multiplier', sa.Float(), nullable=True),
    sa.Column('temp_exp_multiplier', sa.Float(), nullable=True),
    sa.Column('base_coins_multiplier', sa.Float(), nullable=True),
    sa.Column('temp_coins_multipler', sa.Float(), nullable=True),
    sa.Column('bonus_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('level_roles', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_table('guildloggingconfig',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('bans_log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('clans_log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('members_log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('messages_log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('voices_log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('moderation_log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('tickets_log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('roles_log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('channels_log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('reactions_log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('private_rooms_log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('economy_log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('message_log_ignoring_channels_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_table('guildmoderationconfig',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('moderation_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('count_moderator_messages_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('ban_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('mute_score', sa.Float(), nullable=True),
    sa.Column('ban_score', sa.Float(), nullable=True),
    sa.Column('kick_score', sa.Float(), nullable=True),
    sa.Column('ticket_score', sa.Float(), nullable=True),
    sa.Column('role_request_score', sa.Float(), nullable=True),
    sa.Column('role_remove_score', sa.Float(), nullable=True),
    sa.Column('ticket_ban_score', sa.Float(), nullable=True),
    sa.Column('mpmute_score', sa.Float(), nullable=True),
    sa.Column('vmute_score', sa.Float(), nullable=True),
    sa.Column('message_score', sa.Float(), nullable=True),
    sa.Column('trackable_moderation_role_id', sa.BigInteger(), nullable=True),
    sa.Column('ban_request_ping_role_id', sa.BigInteger(), nullable=True),
    sa.Column('send_ban_request_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('mpmute_role_id', sa.BigInteger(), nullable=True),
    sa.Column('vmute_role_id', sa.BigInteger(), nullable=True),
    sa.Column('mute_role_id', sa.BigInteger(), nullable=True),
    sa.Column('mute_type', sa.String(), nullable=False),
    sa.Column('fraction_roles_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('leader_access_rr_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_table('guildnotificationsconfig',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('notifications_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('notifications_for_moderation_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('notifications_from_bot_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_table('guildprivatechannelsconfig',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('private_rooms_create_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_table('guildticketsconfig',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('tickets_count', sa.Integer(), nullable=False),
    sa.Column('new_tickets_category_id', sa.BigInteger(), nullable=True),
    sa.Column('closed_tickets_category_id', sa.BigInteger(), nullable=True),
    sa.Column('create_ticket_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('pinned_tickets_category_id', sa.BigInteger(), nullable=True),
    sa.Column('create_ticket_ping_role_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_table('mainguildconfig',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('rules_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('create_proposal_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('proposals_count', sa.Integer(), nullable=False),
    sa.Column('organizational_roles', sa.JSON(), nullable=False),
    sa.Column('fraction_roles', sa.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('voice_temp_roles', sa.JSON(), nullable=False),
    sa.Column('faq', sa.JSON(), nullable=False),
    sa.Column('check_role_requests_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_table('punish',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('used_id', sa.BigInteger(), nullable=False),
    sa.Column('moderator_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('end_time', sa.Integer(), nullable=True),
    sa.Column('time_now', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('coins', sa.Float(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('current_exp', sa.BigInteger(), nullable=False),
    sa.Column('exp_to_level', sa.BigInteger(), nullable=False),
    sa.Column('voice_activity', sa.BigInteger(), nullable=False),
    sa.Column('temp_voice_activity', sa.DateTime(), nullable=True),
    sa.Column('reward_time', sa.SmallInteger(), nullable=False),
    sa.Column('ticket_ban', sa.Boolean(), nullable=False),
    sa.Column('ban_role_request', sa.Boolean(), nullable=False),
    sa.Column('battle_pass_level', sa.Integer(), nullable=False),
    sa.Column('battle_pass_points', sa.Float(), nullable=False),
    sa.Column('inventory', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('punish')
    op.drop_table('mainguildconfig')
    op.drop_table('guildticketsconfig')
    op.drop_table('guildprivatechannelsconfig')
    op.drop_table('guildnotificationsconfig')
    op.drop_table('guildmoderationconfig')
    op.drop_table('guildloggingconfig')
    op.drop_table('guildlevelsconfig')
    op.drop_table('guildeconomyconfig')
    op.drop_table('guildclansconfig')
    op.drop_table('clan')
    # ### end Alembic commands ###
