"""Fri Oct 31 11:27:17 PM CET 2025

Revision ID: 24780dd63de2
Revises: e3b3c25bc7e5
Create Date: 2025-10-31 23:27:23.376316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24780dd63de2'
down_revision: Union[str, Sequence[str], None] = 'e3b3c25bc7e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_user_id_key'), 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_user_id_key'), 'user', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
