"""Mon Oct 20 09:51:16 PM CEST 2025

Revision ID: 26db324cb473
Revises: 1f8941859ed8
Create Date: 2025-10-20 21:51:18.269903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26db324cb473'
down_revision: Union[str, Sequence[str], None] = '1f8941859ed8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_clan_guild_id'), 'clan', ['guild_id'], unique=False)
    op.create_unique_constraint('uq_clan_guild_name', 'clan', ['guild_id', 'name'])
    op.create_index(op.f('ix_clanmember_clan_id'), 'clanmember', ['clan_id'], unique=False)
    op.create_index(op.f('ix_clanmember_guild_id'), 'clanmember', ['guild_id'], unique=False)
    op.create_index(op.f('ix_clanmember_user_id'), 'clanmember', ['user_id'], unique=False)
    op.create_unique_constraint('uq_member_guild_user', 'clanmember', ['guild_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_member_guild_user', 'clanmember', type_='unique')
    op.drop_index(op.f('ix_clanmember_user_id'), table_name='clanmember')
    op.drop_index(op.f('ix_clanmember_guild_id'), table_name='clanmember')
    op.drop_index(op.f('ix_clanmember_clan_id'), table_name='clanmember')
    op.drop_constraint('uq_clan_guild_name', 'clan', type_='unique')
    op.drop_index(op.f('ix_clan_guild_id'), table_name='clan')
    # ### end Alembic commands ###
