"""Thu Oct 30 07:29:11 PM CET 2025

Revision ID: 2833f3bd6c93
Revises: 2e7d69ca6c47
Create Date: 2025-10-30 19:29:12.417722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2833f3bd6c93'
down_revision: Union[str, Sequence[str], None] = '2e7d69ca6c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
