"""add base/temp_battlepass_multiplier

Revision ID: 294b6bab8716
Revises: 03059ad0efa7
Create Date: 2025-12-29 16:24:17.346910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '294b6bab8716'
down_revision: Union[str, Sequence[str], None] = '03059ad0efa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guildlevelsconfig', sa.Column('base_battlepass_multiplier', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.add_column('guildlevelsconfig', sa.Column('temp_battlepass_multiplier', sa.Integer(), nullable=True))
    op.alter_column('tempeconomymultiplier', 'multiplier_type',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Enum('exp', 'coins', 'battlepass', name='multipliertypeenum', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tempeconomymultiplier', 'multiplier_type',
               existing_type=sa.Enum('exp', 'coins', 'battlepass', name='multipliertypeenum', native_enum=False),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    op.drop_column('guildlevelsconfig', 'temp_battlepass_multiplier')
    op.drop_column('guildlevelsconfig', 'base_battlepass_multiplier')
    # ### end Alembic commands ###
