""" add moderationmessage

Revision ID: 2c78daa4fc1a
Revises: 8f1a60b4d12f
Create Date: 2025-11-08 16:42:30.299045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c78daa4fc1a'
down_revision: Union[str, Sequence[str], None] = '8f1a60b4d12f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temp_economy_multipliers_guild_type_end_time'), table_name='tempeconomymultiplier')
    op.create_index('ix_temp_economy_multipliers_guild_type_end_time', 'tempeconomymultiplier', ['guild_id', 'multiplier_type'], unique=False)
    op.create_index('ix_temp_economy_multipliers_end_time', 'tempeconomymultiplier', ['end_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_temp_economy_multipliers_end_time', table_name='tempeconomymultiplier')
    op.drop_index('ix_temp_economy_multipliers_guild_type_end_time', table_name='tempeconomymultiplier')
    op.create_index(op.f('ix_temp_economy_multipliers_guild_type_end_time'), 'tempeconomymultiplier', ['guild_id', 'multiplier_type', 'end_time'], unique=False)
    # ### end Alembic commands ###
