"""Thu Oct 30 07:02:08 PM CET 2025

Revision ID: 2e7d69ca6c47
Revises: de705820b328
Create Date: 2025-10-30 19:02:13.725780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e7d69ca6c47'
down_revision: Union[str, Sequence[str], None] = 'de705820b328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
