"""Revision (Tue Aug 18 12:47:41 CEST 2026)

Revision ID: 3775d2b02a45
Revises: a8720df54ac2
Create Date: 2026-08-18 12:47:41.642865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3775d2b02a45'
down_revision: Union[str, Sequence[str], None] = 'a8720df54ac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    old_bonuses = bind.execute(
        sa.text(
            "SELECT guild_id, reward_bonus FROM guildeconomyconfig"
            " WHERE reward_bonus > 0"
        )
    ).mappings().all()

    op.create_table('guildrewardbonus',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guildeconomyconfig.guild_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'role_id', deferrable=True, initially='DEFERRED', name='uq_reward_bonus_guild')
    )

    for row in old_bonuses:
        op.execute(
            sa.text(
                "INSERT INTO guildrewardbonus (guild_id, coins, role_id)"
                " VALUES (:guild_id, :coins, NULL)"
            ).bindparams(guild_id=row["guild_id"], coins=row["reward_bonus"])
        )

    op.drop_column('guildeconomyconfig', 'reward_bonus')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guildeconomyconfig', sa.Column('reward_bonus', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.execute(
        sa.text(
            "UPDATE guildeconomyconfig g SET reward_bonus = COALESCE(("
            "  SELECT b.coins FROM guildrewardbonus b"
            "  WHERE b.guild_id = g.guild_id AND b.role_id IS NULL"
            "  LIMIT 1), 0)"
        )
    )
    op.drop_table('guildrewardbonus')
    # ### end Alembic commands ###
