"""Fri Sep 19 09:34:01 PM CEST 2025

Revision ID: 3987deacccd3
Revises: 792d2c22ff35
Create Date: 2025-09-19 21:34:02.898545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3987deacccd3'
down_revision: Union[str, Sequence[str], None] = '792d2c22ff35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticketstate', 'state',
               existing_type=postgresql.ENUM('OPEN', 'IN_PROGRESS', 'CLOSED', name='ticketstateenum'),
               type_=sa.Enum('opened', 'pinned', 'closed', name='ticketstateenum', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticketstate', 'state',
               existing_type=sa.Enum('opened', 'pinned', 'closed', name='ticketstateenum', native_enum=False),
               type_=postgresql.ENUM('OPEN', 'IN_PROGRESS', 'CLOSED', name='ticketstateenum'),
               existing_nullable=False)
    # ### end Alembic commands ###
