"""Sat Sep 13 05:28:40 PM CEST 2025

Revision ID: 3aeae0e45d73
Revises: c36d7f070603
Create Date: 2025-09-13 17:28:46.902588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aeae0e45d73'
down_revision: Union[str, Sequence[str], None] = 'c36d7f070603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guildmoderationconfig', sa.Column('leadership_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guildmoderationconfig', 'leadership_access_roles_ids')
    # ### end Alembic commands ###
