"""Mon Oct 27 02:53:54 PM CET 2025

Revision ID: 3e3c7307f707
Revises: 46aa1cd9f806
Create Date: 2025-10-27 14:53:55.458088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e3c7307f707'
down_revision: Union[str, Sequence[str], None] = '46aa1cd9f806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
