"""Revision (Tue Aug 18 18:08:13 CEST 2026)

Revision ID: 3e650f60e04b
Revises: 3775d2b02a45
Create Date: 2026-08-18 18:08:14.287297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e650f60e04b'
down_revision: Union[str, Sequence[str], None] = '3775d2b02a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guildeconomyconfig', sa.Column('base_reward_bonus', sa.Integer(), server_default=sa.text('0'), nullable=False))

    op.execute(
        sa.text(
            "UPDATE guildeconomyconfig g SET base_reward_bonus = COALESCE(("
            "  SELECT b.coins FROM guildrewardbonus b"
            "  WHERE b.guild_id = g.guild_id AND b.role_id IS NULL"
            "  LIMIT 1), 0)"
        )
    )

    op.execute(sa.text("DELETE FROM guildrewardbonus WHERE role_id IS NULL"))

    op.alter_column('guildrewardbonus', 'role_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guildrewardbonus', 'role_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    op.execute(
        sa.text(
            "INSERT INTO guildrewardbonus (guild_id, coins, role_id)"
            " SELECT guild_id, base_reward_bonus, NULL FROM guildeconomyconfig"
            " WHERE base_reward_bonus > 0"
        )
    )

    op.drop_column('guildeconomyconfig', 'base_reward_bonus')
    # ### end Alembic commands ###
