"""Sat Aug 16 07:46:06 PM CEST 2025

Revision ID: 420dd27cef77
Revises: 19555e7360c3
Create Date: 2025-08-16 19:46:07.768324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '420dd27cef77'
down_revision: Union[str, Sequence[str], None] = '19555e7360c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guildconfig', sa.Column('fraction_roles_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guildconfig', 'fraction_roles_access_roles_ids')
    # ### end Alembic commands ###
