"""Revision (Thu Aug 20 17:24:52 CEST 2026)

Revision ID: 441bca2e3e5b
Revises: 91c8f39090db
Create Date: 2026-08-20 17:24:52.948690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '441bca2e3e5b'
down_revision: Union[str, Sequence[str], None] = '91c8f39090db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loggingrevision', sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loggingrevision', 'version')
    # ### end Alembic commands ###
