"""Mon Oct 27 02:45:57 PM CET 2025

Revision ID: 46aa1cd9f806
Revises: 6c7ad3eafe68
Create Date: 2025-10-27 14:46:02.569877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46aa1cd9f806'
down_revision: Union[str, Sequence[str], None] = '6c7ad3eafe68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guildeconomyconfig', sa.Column('economy_shop_channel_id', sa.BigInteger(), nullable=True))
    op.add_column(
        'guildeconomyconfig',
        sa.Column(
            'economy_shop_items',
            sa.JSON(),
            nullable=False,
            server_default=sa.text("'[]'::json")
        )
    )
    op.drop_column('guildeconomyconfig', 'economy_shop')
    op.drop_column('guildeconomyconfig', 'economy_products')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guildeconomyconfig', sa.Column('economy_products', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('guildeconomyconfig', sa.Column('economy_shop', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('guildeconomyconfig', 'economy_shop_items')
    op.drop_column('guildeconomyconfig', 'economy_shop_channel_id')
    # ### end Alembic commands ###
