"""Thu Oct 30 07:32:48 PM CET 2025

Revision ID: 4b32380ab165
Revises: 2833f3bd6c93
Create Date: 2025-10-30 19:32:49.888987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b32380ab165'
down_revision: Union[str, Sequence[str], None] = '2833f3bd6c93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
