"""Mon Oct 13 05:06:58 PM CEST 2025

Revision ID: 4eba63d7d3d6
Revises: b8dee0126dd7
Create Date: 2025-10-13 17:07:04.560215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eba63d7d3d6'
down_revision: Union[str, Sequence[str], None] = 'b8dee0126dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'mainguildconfig',
        sa.Column(
            'guild_rules',
            sa.JSON(),
            nullable=False,
            server_default=sa.text("'{}'::json")  # default empty JSON object
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mainguildconfig', 'guild_rules')
    # ### end Alembic commands ###
