"""add unban_access_roles_ids

Revision ID: 5059b32db108
Revises: 294b6bab8716
Create Date: 2026-01-01 17:36:24.578266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5059b32db108'
down_revision: Union[str, Sequence[str], None] = '294b6bab8716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guildmoderationconfig', sa.Column('unban_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guildmoderationconfig', 'unban_access_roles_ids')
    # ### end Alembic commands ###
