"""Mon Oct 20 07:47:45 PM CEST 2025

Revision ID: 5492e9e0eb7f
Revises: d10cf3da429b
Create Date: 2025-10-20 19:47:46.281674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5492e9e0eb7f'
down_revision: Union[str, Sequence[str], None] = 'd10cf3da429b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clan', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clan', 'name')
    # ### end Alembic commands ###
