"""Wed Oct 29 08:44:30 PM CET 2025

Revision ID: 58711f53ff03
Revises: a5515edc0cd7
Create Date: 2025-10-29 20:44:35.309485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58711f53ff03'
down_revision: Union[str, Sequence[str], None] = 'a5515edc0cd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guildeconomyconfig', sa.Column('drop_from_coins_case', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=False))
    op.add_column('guildeconomyconfig', sa.Column('drop_from_colors_case', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=False))
    op.drop_column('guildeconomyconfig', 'drop_from_cases')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guildeconomyconfig', sa.Column('drop_from_cases', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('guildeconomyconfig', 'drop_from_colors_case')
    op.drop_column('guildeconomyconfig', 'drop_from_coins_case')
    # ### end Alembic commands ###
