"""Mon Oct 20 06:21:06 PM CEST 2025

Revision ID: 6243905c070e
Revises: bcb6e1604b55
Create Date: 2025-10-20 18:21:13.496247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6243905c070e'
down_revision: Union[str, Sequence[str], None] = 'bcb6e1604b55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guildclansconfig', sa.Column('clan_shop_items', sa.JSON(), nullable=False))
    op.add_column('guildclansconfig', sa.Column('clans_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True))
    op.add_column('guildclansconfig', sa.Column('clan_reputation_per_payday', sa.Float(), nullable=False))
    op.drop_column('guildclansconfig', 'clan_reputation')
    op.drop_column('guildclansconfig', 'clan_shop_products')
    op.drop_column('guildclansconfig', 'clan_access_roles_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guildclansconfig', sa.Column('clan_access_roles_ids', postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=True))
    op.add_column('guildclansconfig', sa.Column('clan_shop_products', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('guildclansconfig', sa.Column('clan_reputation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('guildclansconfig', 'clan_reputation_per_payday')
    op.drop_column('guildclansconfig', 'clans_access_roles_ids')
    op.drop_column('guildclansconfig', 'clan_shop_items')
    # ### end Alembic commands ###
