"""Revision (Sun Feb 15 20:16:16 CET 2026)

Revision ID: 69331e65c4dc
Revises: b30dc2cbfbe0
Create Date: 2026-02-15 20:16:17.994087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69331e65c4dc'
down_revision: Union[str, Sequence[str], None] = 'b30dc2cbfbe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guildclansconfig', sa.Column('create_clan_channel_category_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guildclansconfig', 'create_clan_channel_category_id')
    # ### end Alembic commands ###
