"""Sat Oct 25 07:55:14 PM CEST 2025

Revision ID: 6c7ad3eafe68
Revises: db6382b98881
Create Date: 2025-10-25 19:55:21.593748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c7ad3eafe68'
down_revision: Union[str, Sequence[str], None] = 'db6382b98881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shoporderstate',
    sa.Column('custom_id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.Enum('pending', 'approved', 'denied', name='shoporderstateenum', native_enum=False), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shoporderstate')
    # ### end Alembic commands ###
