"""Revision (Mon Feb 16 10:28:52 CET 2026)

Revision ID: 70a2b7a2986a
Revises: 69331e65c4dc
Create Date: 2026-02-16 10:28:53.409467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70a2b7a2986a'
down_revision: Union[str, Sequence[str], None] = '69331e65c4dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clan', sa.Column('clan_channel_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'clan', ['clan_channel_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clan', type_='unique')
    op.drop_column('clan', 'clan_channel_id')
    # ### end Alembic commands ###
