"""Wed Sep 24 05:44:30 PM CEST 2025

Revision ID: 749e62e78681
Revises: 10c41d7cd808
Create Date: 2025-09-24 17:44:32.179953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '749e62e78681'
down_revision: Union[str, Sequence[str], None] = '10c41d7cd808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_request_ban', sa.Boolean(), nullable=False))
    op.drop_column('user', 'ban_role_request')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ban_role_request', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'role_request_ban')
    # ### end Alembic commands ###
