"""Tue Sep 16 08:46:32 PM CEST 2025

Revision ID: 7684ad792aae
Revises: 3aeae0e45d73
Create Date: 2025-09-16 20:46:35.652810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7684ad792aae'
down_revision: Union[str, Sequence[str], None] = '3aeae0e45d73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ux_user_guild_user', 'user', ['guild_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ux_user_guild_user', 'user', type_='unique')
    # ### end Alembic commands ###
