"""Sat Aug 16 06:23:50 PM CEST 2025

Revision ID: 7826864e1d9f
Revises: 74e28b04c0c0
Create Date: 2025-08-16 18:23:52.746598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7826864e1d9f'
down_revision: Union[str, Sequence[str], None] = '74e28b04c0c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
