"""Sat Nov  1 11:39:44 PM CET 2025

Revision ID: 784ae334b2f8
Revises: 7d0b869785bc
Create Date: 2025-11-01 23:39:46.031968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '784ae334b2f8'
down_revision: Union[str, Sequence[str], None] = '7d0b869785bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
