"""Fri Sep 19 09:15:16 PM CEST 2025

Revision ID: 792d2c22ff35
Revises: a5d8b1b47e1e
Create Date: 2025-09-19 21:15:18.160147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '792d2c22ff35'
down_revision: Union[str, Sequence[str], None] = 'a5d8b1b47e1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticketstate', 'moderator_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticketstate', 'moderator_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
