"""Sat Nov  1 07:14:05 PM CET 2025

Revision ID: 7d0b869785bc
Revises: 24780dd63de2
Create Date: 2025-11-01 19:14:10.620970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d0b869785bc'
down_revision: Union[str, Sequence[str], None] = '24780dd63de2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guildeconomyconfig', sa.Column('battlepass_rewards', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guildeconomyconfig', 'battlepass_rewards')
    # ### end Alembic commands ###
