"""Thu Aug 21 10:39:22 PM CEST 2025

Revision ID: 7ff83ff61826
Revises: 17a45cbbbb6b
Create Date: 2025-08-21 22:39:23.307992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ff83ff61826'
down_revision: Union[str, Sequence[str], None] = '17a45cbbbb6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('punish', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.drop_column('punish', 'used_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('punish', sa.Column('used_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('punish', 'user_id')
    # ### end Alembic commands ###
