"""Thu Oct  2 09:56:44 PM CEST 2025

Revision ID: 8044bf27a0f9
Revises: abd8c97b9fd3
Create Date: 2025-10-02 21:56:50.283662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8044bf27a0f9'
down_revision: Union[str, Sequence[str], None] = 'abd8c97b9fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('punish', sa.Column('original_duration', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('punish', 'original_duration')
    # ### end Alembic commands ###
