"""Tue Oct 28 10:46:07 PM CET 2025

Revision ID: 8202b21b3c8d
Revises: 8beebb7de371
Create Date: 2025-10-28 22:46:08.678885

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '8202b21b3c8d'
down_revision: Union[str, Sequence[str], None] = '8beebb7de371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop old column and create new one with correct type
    # (since converting SMALLINT to DateTime doesn't make sense - set to NULL)
    op.execute("ALTER TABLE \"user\" ALTER COLUMN reward_time DROP NOT NULL")
    op.execute("ALTER TABLE \"user\" ALTER COLUMN reward_time TYPE TIMESTAMP WITH TIME ZONE USING NULL")

    op.create_unique_constraint(None, 'user', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_user_id_key', 'user', type_='unique')

    # Convert DateTime back to SMALLINT (set to 0 as default)
    op.execute("ALTER TABLE \"user\" ALTER COLUMN reward_time TYPE SMALLINT USING 0")
    op.execute("ALTER TABLE \"user\" ALTER COLUMN reward_time SET NOT NULL")
    # ### end Alembic commands ###
