"""Sat Aug  9 07:08:10 PM CEST 2025

Revision ID: 87fd87c2ef1b
Revises: 99a5f04d0ec5
Create Date: 2025-08-09 19:08:11.446768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87fd87c2ef1b'
down_revision: Union[str, Sequence[str], None] = '99a5f04d0ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guildconfig', sa.Column('voices_log_channel_id', sa.BigInteger(), nullable=True))
    op.drop_column('guildconfig', 'voice_log_channel_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guildconfig', sa.Column('voice_log_channel_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('guildconfig', 'voices_log_channel_id')
    # ### end Alembic commands ###
