"""Thu Aug  7 07:50:19 PM CEST 2025

Revision ID: 8a4b952cb58c
Revises: 33fa38d3433b
Create Date: 2025-08-07 19:50:20.208110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a4b952cb58c'
down_revision: Union[str, Sequence[str], None] = '33fa38d3433b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guildconfig', 'ban_log_channel_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('guildconfig', 'clan_log_channel_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('guildconfig', 'members_update_log_channel_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('guildconfig', 'messages_log_channel_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('guildconfig', 'voice_log_channel_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('guildconfig', 'moderation_log_channel_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('guildconfig', 'count_moderator_messages_channel_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('guildconfig', 'ticket_log_channel_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('guildconfig', 'roles_log_channel_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('guildconfig', 'channels_log_channel_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('guildconfig', 'coin_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('guildconfig', 'economy_access_roles_ids',
               existing_type=postgresql.ARRAY(sa.BIGINT()),
               nullable=True)
    op.alter_column('guildconfig', 'reward_count',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('guildconfig', 'coins_multipler',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('guildconfig', 'temp_coins_multipler',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('guildconfig', 'economy_shop_buy_ping_roles_ids',
               existing_type=postgresql.ARRAY(sa.BIGINT()),
               nullable=True)
    op.alter_column('guildconfig', 'count_messages_channel_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('guildconfig', 'level_notify_channel_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('guildconfig', 'exp_multipler',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('guildconfig', 'temp_exp_multipler',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('guildconfig', 'bonus_roles_ids',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('guildconfig', 'clan_payday_channel_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('guildconfig', 'clan_shop_channel_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('guildconfig', 'clan_access_roles_ids',
               existing_type=postgresql.ARRAY(sa.BIGINT()),
               nullable=True)
    op.alter_column('guildconfig', 'create_clan_role_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('guildconfig', 'clan_buy_ping_roles_ids',
               existing_type=postgresql.ARRAY(sa.BIGINT()),
               nullable=True)
    op.alter_column('guildconfig', 'private_rooms_create_channel_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('guildconfig', 'moderation_access_roles_ids',
               existing_type=postgresql.ARRAY(sa.BIGINT()),
               nullable=True)
    op.alter_column('guildconfig', 'ban_access_roles_ids',
               existing_type=postgresql.ARRAY(sa.BIGINT()),
               nullable=True)
    op.alter_column('guildconfig', 'mute_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('guildconfig', 'ban_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('guildconfig', 'kick_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('guildconfig', 'ticket_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('guildconfig', 'role_request_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('guildconfig', 'role_remove_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('guildconfig', 'ticket_ban_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('guildconfig', 'mpmute_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('guildconfig', 'vmute_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('guildconfig', 'message_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('guildconfig', 'trackable_moderation_role_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('guildconfig', 'ban_request_ping_role_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('guildconfig', 'send_ban_request_channel_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('guildconfig', 'notifications_channel_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('guildconfig', 'notifications_for_moderation_channel_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('guildconfig', 'notifications_from_bot_channel_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('guildconfig', 'new_tickets_category_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('guildconfig', 'closed_tickets_category_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('guildconfig', 'create_ticket_channel_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('guildconfig', 'pinned_tickets_category_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('guildconfig', 'check_role_requests_channel_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('guildconfig', 'create_ticket_ping_role_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('guildconfig', 'create_proposal_channel_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('guildconfig', 'mpmute_role_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('guildconfig', 'vmute_role_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('guildconfig', 'rules_channel_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('guildconfig', 'drop_from_cases',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('guildconfig', 'embed_config_access_roles',
               existing_type=postgresql.ARRAY(sa.BIGINT()),
               nullable=True)
    op.alter_column('guildconfig', 'message_log_ignoring_channels_ids',
               existing_type=postgresql.ARRAY(sa.BIGINT()),
               nullable=True)
    op.alter_column('guildconfig', 'mute_role_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('guildconfig', 'economy_log_channel_id')
    op.drop_column('guildconfig', 'private_rooms_log_channel_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guildconfig', sa.Column('private_rooms_log_channel_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('guildconfig', sa.Column('economy_log_channel_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.alter_column('guildconfig', 'mute_role_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('guildconfig', 'message_log_ignoring_channels_ids',
               existing_type=postgresql.ARRAY(sa.BIGINT()),
               nullable=False)
    op.alter_column('guildconfig', 'embed_config_access_roles',
               existing_type=postgresql.ARRAY(sa.BIGINT()),
               nullable=False)
    op.alter_column('guildconfig', 'drop_from_cases',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('guildconfig', 'rules_channel_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('guildconfig', 'vmute_role_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('guildconfig', 'mpmute_role_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('guildconfig', 'create_proposal_channel_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('guildconfig', 'create_ticket_ping_role_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('guildconfig', 'check_role_requests_channel_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('guildconfig', 'pinned_tickets_category_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('guildconfig', 'create_ticket_channel_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('guildconfig', 'closed_tickets_category_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('guildconfig', 'new_tickets_category_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('guildconfig', 'notifications_from_bot_channel_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('guildconfig', 'notifications_for_moderation_channel_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('guildconfig', 'notifications_channel_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('guildconfig', 'send_ban_request_channel_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('guildconfig', 'ban_request_ping_role_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('guildconfig', 'trackable_moderation_role_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('guildconfig', 'message_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('guildconfig', 'vmute_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('guildconfig', 'mpmute_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('guildconfig', 'ticket_ban_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('guildconfig', 'role_remove_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('guildconfig', 'role_request_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('guildconfig', 'ticket_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('guildconfig', 'kick_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('guildconfig', 'ban_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('guildconfig', 'mute_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('guildconfig', 'ban_access_roles_ids',
               existing_type=postgresql.ARRAY(sa.BIGINT()),
               nullable=False)
    op.alter_column('guildconfig', 'moderation_access_roles_ids',
               existing_type=postgresql.ARRAY(sa.BIGINT()),
               nullable=False)
    op.alter_column('guildconfig', 'private_rooms_create_channel_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('guildconfig', 'clan_buy_ping_roles_ids',
               existing_type=postgresql.ARRAY(sa.BIGINT()),
               nullable=False)
    op.alter_column('guildconfig', 'create_clan_role_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('guildconfig', 'clan_access_roles_ids',
               existing_type=postgresql.ARRAY(sa.BIGINT()),
               nullable=False)
    op.alter_column('guildconfig', 'clan_shop_channel_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('guildconfig', 'clan_payday_channel_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('guildconfig', 'bonus_roles_ids',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('guildconfig', 'temp_exp_multipler',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('guildconfig', 'exp_multipler',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('guildconfig', 'level_notify_channel_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('guildconfig', 'count_messages_channel_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('guildconfig', 'economy_shop_buy_ping_roles_ids',
               existing_type=postgresql.ARRAY(sa.BIGINT()),
               nullable=False)
    op.alter_column('guildconfig', 'temp_coins_multipler',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('guildconfig', 'coins_multipler',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('guildconfig', 'reward_count',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('guildconfig', 'economy_access_roles_ids',
               existing_type=postgresql.ARRAY(sa.BIGINT()),
               nullable=False)
    op.alter_column('guildconfig', 'coin_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('guildconfig', 'channels_log_channel_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('guildconfig', 'roles_log_channel_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('guildconfig', 'ticket_log_channel_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('guildconfig', 'count_moderator_messages_channel_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('guildconfig', 'moderation_log_channel_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('guildconfig', 'voice_log_channel_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('guildconfig', 'messages_log_channel_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('guildconfig', 'members_update_log_channel_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('guildconfig', 'clan_log_channel_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('guildconfig', 'ban_log_channel_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
