"""Mon Sep  1 08:51:10 PM CEST 2025

Revision ID: 8a98275fef79
Revises: 443c94bb242a
Create Date: 2025-09-01 20:51:15.826752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a98275fef79'
down_revision: Union[str, Sequence[str], None] = '443c94bb242a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('punish', 'time_now',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index('ix_punish_guild_user_time_now', 'punish', ['guild_id', 'user_id', 'time_now'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_punish_guild_user_time_now', table_name='punish')
    op.alter_column('punish', 'time_now',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###
