"""Tue Oct 28 10:33:51 PM CET 2025

Revision ID: 8beebb7de371
Revises: cd22d68ffa80
Create Date: 2025-10-28 22:33:53.417478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8beebb7de371'
down_revision: Union[str, Sequence[str], None] = 'cd22d68ffa80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Step 1: Update all NULL values to 0 (or your default value)
    op.execute("UPDATE guildeconomyconfig SET reward_bonus = 0 WHERE reward_bonus IS NULL")

    # Step 2: Change column type and set NOT NULL
    op.alter_column('guildeconomyconfig', 'reward_bonus',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guildeconomyconfig', 'reward_bonus',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
