"""improve casino

Revision ID: 8e6e4b99f529
Revises: 5059b32db108
Create Date: 2026-01-12 17:36:04.903490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e6e4b99f529'
down_revision: Union[str, Sequence[str], None] = '5059b32db108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casinogame',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('initiator_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('game_type', sa.Enum('roulette', name='casinogametypeenum', native_enum=False), nullable=False),
    sa.Column('players_type', sa.Enum('single', 'multiplayer', name='casinoplayerstypeenum', native_enum=False), nullable=False),
    sa.Column('state', sa.Enum('pending', 'finished', name='casinogamestateenum', native_enum=False), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_casinogame_guild_id'), 'casinogame', ['guild_id'], unique=False)
    op.create_table('casinobet',
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('result_type', sa.Enum('win', 'lose', name='casinobetresulttypeenum', native_enum=False), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['casinogame.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_casinobet_game_id'), 'casinobet', ['game_id'], unique=False)
    op.create_index(op.f('ix_casinobet_user_id'), 'casinobet', ['user_id'], unique=False)
    op.add_column('guildeconomyconfig', sa.Column('casino_multiplayer_channel_id', sa.BigInteger(), nullable=True))
    op.drop_column('guildeconomyconfig', 'last_roulette_games')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guildeconomyconfig', sa.Column('last_roulette_games', postgresql.ARRAY(sa.VARCHAR()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=False))
    op.drop_column('guildeconomyconfig', 'casino_multiplayer_channel_id')
    op.drop_index(op.f('ix_casinobet_user_id'), table_name='casinobet')
    op.drop_index(op.f('ix_casinobet_game_id'), table_name='casinobet')
    op.drop_table('casinobet')
    op.drop_index(op.f('ix_casinogame_guild_id'), table_name='casinogame')
    op.drop_table('casinogame')
    # ### end Alembic commands ###
