""" add moderationmessage

Revision ID: 8f1a60b4d12f
Revises: dca95826d845
Create Date: 2025-11-08 16:38:08.123300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f1a60b4d12f'
down_revision: Union[str, Sequence[str], None] = 'dca95826d845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderationmessage',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('moderator_id', sa.BigInteger(), nullable=False),
    sa.Column('time_now', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_moderationmessages_guild_id_moderator_id_time_now', 'moderationmessage', ['guild_id', 'moderator_id', 'time_now'], unique=False)
    op.alter_column('changestat', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('changestat', 'amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index('ix_moderationmessages_guild_id_moderator_id_time_now', table_name='moderationmessage')
    op.drop_table('moderationmessage')
    # ### end Alembic commands ###
