"""Revision (Thu Aug 20 14:23:25 CEST 2026)

Revision ID: 91c8f39090db
Revises: bbd438c928b3
Create Date: 2026-08-20 14:23:25.691122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91c8f39090db'
down_revision: Union[str, Sequence[str], None] = 'bbd438c928b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loggingrevision', sa.Column('data', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False))
    op.drop_column('loggingrevision', 'new_data')
    op.drop_column('loggingrevision', 'old_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loggingrevision', sa.Column('old_data', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False))
    op.add_column('loggingrevision', sa.Column('new_data', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False))
    op.drop_column('loggingrevision', 'data')
    # ### end Alembic commands ###
