"""fix_user_inventory

Revision ID: 942ff738079f
Revises: 58711f53ff03
Create Date: 2025-10-29 21:23:19.075131

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '942ff738079f'
down_revision: Union[str, Sequence[str], None] = '58711f53ff03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
