"""Sun Sep 28 08:49:06 PM CEST 2025

Revision ID: 971961b7126d
Revises: d676c79bfe45
Create Date: 2025-09-28 20:49:12.949210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '971961b7126d'
down_revision: Union[str, Sequence[str], None] = 'd676c79bfe45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.create_index('idx_rr_author_updated_desc', 'rolerequeststate', ['author_id', sa.literal_column('updated_at DESC')], unique=False, postgresql_concurrently=True)
        op.create_index('idx_rr_guild_author_updated_desc', 'rolerequeststate', ['guild_id', 'author_id', sa.literal_column('updated_at DESC')], unique=False, postgresql_concurrently=True)
        op.create_index('idx_ticket_guild_author_updated_desc', 'ticketstate', ['guild_id', 'author_id', sa.literal_column('updated_at DESC')], unique=False, postgresql_concurrently=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.drop_index('idx_ticket_guild_author_updated_desc', table_name='ticketstate', postgresql_concurrently=True)
        op.drop_index('idx_rr_guild_author_updated_desc', table_name='rolerequeststate', postgresql_concurrently=True)
        op.drop_index('idx_rr_author_updated_desc', table_name='rolerequeststate', postgresql_concurrently=True)
    # ### end Alembic commands ###
