"""Sat Aug  9 06:27:06 PM CEST 2025

Revision ID: 99a5f04d0ec5
Revises: 8a4b952cb58c
Create Date: 2025-08-09 18:27:07.231697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99a5f04d0ec5'
down_revision: Union[str, Sequence[str], None] = '8a4b952cb58c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guildconfig', sa.Column('members_log_channel_id', sa.BigInteger(), nullable=True))
    op.add_column('guildconfig', sa.Column('tickets_log_channel_id', sa.BigInteger(), nullable=True))
    op.drop_column('guildconfig', 'ticket_log_channel_id')
    op.drop_column('guildconfig', 'members_update_log_channel_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guildconfig', sa.Column('members_update_log_channel_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('guildconfig', sa.Column('ticket_log_channel_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('guildconfig', 'tickets_log_channel_id')
    op.drop_column('guildconfig', 'members_log_channel_id')
    # ### end Alembic commands ###
