"""bank system

Revision ID: 9d004a16c046
Revises: cb335ac39147
Create Date: 2026-09-28 10:38:45.186545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d004a16c046'
down_revision: Union[str, Sequence[str], None] = 'cb335ac39147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bankaccount',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'user_id', name='ux_user_guild_bank_account')
    )
    op.create_table('deposit',
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('coins', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_accrued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bankaccount.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_account_id')
    )
    op.create_table('extrawallet',
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('coins', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bankaccount.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extrawallet')
    op.drop_table('deposit')
    op.drop_table('bankaccount')
    # ### end Alembic commands ###
