"""coins per level up

Revision ID: a301b75257bc
Revises: c3d90b6a4f18
Create Date: 2026-09-29 13:11:44.189244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a301b75257bc'
down_revision: Union[str, Sequence[str], None] = 'c3d90b6a4f18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guildlevelsconfig', sa.Column('coins_per_level_up', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guildlevelsconfig', 'coins_per_level_up')
    # ### end Alembic commands ###
