""" add illegal_roles

Revision ID: a40e258a0fa0
Revises: 8b7ed44a26a2
Create Date: 2025-11-23 13:54:02.496415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a40e258a0fa0'
down_revision: Union[str, Sequence[str], None] = '8b7ed44a26a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mainguildconfig', sa.Column('illegal_roles', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mainguildconfig', 'illegal_roles')
    # ### end Alembic commands ###
