"""Wed Nov  5 09:28:11 PM CET 2025

Revision ID: a4b966c09412
Revises: f52ae9082436
Create Date: 2025-11-05 21:28:18.930533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4b966c09412'
down_revision: Union[str, Sequence[str], None] = 'f52ae9082436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tempeconomymultiplier',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('multiplier_type', sa.Enum('exp', 'coins', name='multipliertypeenum', native_enum=False), nullable=False),
    sa.Column('multiplier', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'multiplier_type', name='ux_temp_multiplier_guild_type')
    )
    op.create_index('ix_temp_economy_multipliers_guild_type_end_time', 'tempeconomymultiplier', ['guild_id', 'multiplier_type', 'end_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_temp_economy_multipliers_guild_type_end_time', table_name='tempeconomymultiplier')
    op.drop_table('tempeconomymultiplier')
    # ### end Alembic commands ###
