"""Wed Oct 29 01:47:08 PM CET 2025

Revision ID: a5515edc0cd7
Revises: 8202b21b3c8d
Create Date: 2025-10-29 13:47:14.423860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5515edc0cd7'
down_revision: Union[str, Sequence[str], None] = '8202b21b3c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('messages_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.alter_column('user', 'temp_voice_activity',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'temp_voice_activity',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('user', 'messages_count')
    # ### end Alembic commands ###
