"""Wed Sep 17 10:17:50 PM CEST 2025

Revision ID: a5d8b1b47e1e
Revises: 7684ad792aae
Create Date: 2025-09-17 22:17:55.824521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5d8b1b47e1e'
down_revision: Union[str, Sequence[str], None] = '7684ad792aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticketstate',
    sa.Column('ticket_number', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('moderator_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.Enum('OPEN', 'IN_PROGRESS', 'CLOSED', name='ticketstateenum'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticketstate')
    # ### end Alembic commands ###
