"""Revision (Wed Aug 12 12:22:09 CEST 2026)

Revision ID: a8720df54ac2
Revises: ac29fdfc37f1
Create Date: 2026-08-12 12:22:09.430233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8720df54ac2'
down_revision: Union[str, Sequence[str], None] = 'ac29fdfc37f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rainbowrole',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('change_type', sa.Enum('random', 'offset', name='rainbowcolorchangetypeenum', native_enum=False), nullable=False),
    sa.Column('next_change_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', name='ux_guild_rainbow')
    )
    op.alter_column('guildforumconfig', 'prefix_id',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using="prefix_id::boolean")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guildforumconfig', 'prefix_id',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               postgresql_using="prefix_id::integer")
    op.drop_table('rainbowrole')
    # ### end Alembic commands ###
