"""Wed Oct  1 04:33:39 PM CEST 2025

Revision ID: abd8c97b9fd3
Revises: 971961b7126d
Create Date: 2025-10-01 16:33:45.063298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd8c97b9fd3'
down_revision: Union[str, Sequence[str], None] = '971961b7126d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticketstate', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticketstate', 'is_deleted')
    # ### end Alembic commands ###
