"""migrate from jsonb rules to specific tables

Revision ID: ac29fdfc37f1
Revises: bf9f99318dee
Create Date: 2026-06-04 16:49:26.481749

"""
from typing import Any, Sequence, Union, cast

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import json

# revision identifiers, used by Alembic.
revision: str = 'ac29fdfc37f1'
down_revision: Union[str, Sequence[str], None] = 'bf9f99318dee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _load_json_object(raw_value: Any) -> dict[str, Any]:
    if not raw_value:
        return {}

    if isinstance(raw_value, dict):
        return cast(dict[str, Any], raw_value)

    if isinstance(raw_value, str):
        try:
            parsed = json.loads(raw_value)
        except Exception:
            return {}
        if isinstance(parsed, dict):
            return cast(dict[str, Any], parsed)

    return {}


def _load_json_array(raw_value: Any) -> list[dict[str, Any]]:
    if not raw_value:
        return []

    if isinstance(raw_value, list):
        return cast(list[dict[str, Any]], raw_value)

    if isinstance(raw_value, str):
        try:
            parsed = json.loads(raw_value)
        except Exception:
            return []
        if isinstance(parsed, list):
            return cast(list[dict[str, Any]], parsed)

    return []


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guildaccessconfig',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('forum_config_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('org_roles_config_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('proposal_config_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('rules_config_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('multiplers_config_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('logging_config_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('economy_config_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('levels_config_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('clans_config_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('private_channels_config_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('moderation_config_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('notifications_config_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('tickets_config_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('infomaker_config_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_table('guildfaqconfig',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('faq', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    connection = op.get_bind()
    # === migrate faq pages from mainguildconfig ===
    try:
        faq_rows = cast(
            list[dict[str, Any]],
            connection.execute(
                sa.text("SELECT guild_id, faq FROM mainguildconfig")
            ).mappings().all(),
        )
    except Exception:
        faq_rows = []

    migrated_faq_rows = 0
    for row in faq_rows:
        gid = cast(int, row["guild_id"])
        faq_pages = _load_json_array(row.get("faq"))
        if not faq_pages:
            continue

        try:
            connection.execute(
                sa.text(
                    "INSERT INTO guildfaqconfig (guild_id, faq) VALUES (:guild_id, :faq)"
                ),
                {"guild_id": gid, "faq": faq_pages},
            )
            migrated_faq_rows += 1
        except Exception:
            continue

    if migrated_faq_rows:
        print(f"Migrated faq for {migrated_faq_rows} guild(s)")

    op.create_table('guildmultipliersconfig',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('base_exp_multiplier', sa.Integer(), nullable=False),
    sa.Column('temp_exp_multiplier', sa.Integer(), nullable=True),
    sa.Column('base_coins_multiplier', sa.Integer(), nullable=False),
    sa.Column('temp_coins_multiplier', sa.Float(), nullable=True),
    sa.Column('base_battlepass_multiplier', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('temp_battlepass_multiplier', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    # === migrate multipliers from guildlevelsconfig into guildmultipliersconfig ===
    connection = op.get_bind()
    try:
        multiplier_rows = cast(
            list[dict[str, Any]],
            connection.execute(
                sa.text(
                    "SELECT guild_id, base_exp_multiplier, temp_exp_multiplier, base_coins_multiplier, temp_coins_multiplier, base_battlepass_multiplier, temp_battlepass_multiplier FROM guildlevelsconfig"
                )
            ).mappings().all(),
        )
    except Exception:
        multiplier_rows = []

    migrated_multiplier_rows = 0
    for row in multiplier_rows:
        try:
            connection.execute(
                sa.text(
                    "INSERT INTO guildmultipliersconfig (guild_id, base_exp_multiplier, temp_exp_multiplier, base_coins_multiplier, temp_coins_multiplier, base_battlepass_multiplier, temp_battlepass_multiplier) "
                    "VALUES (:guild_id, :base_exp_multiplier, :temp_exp_multiplier, :base_coins_multiplier, :temp_coins_multiplier, :base_battlepass_multiplier, :temp_battlepass_multiplier)"
                ),
                {
                    "guild_id": cast(int, row["guild_id"]),
                    "base_exp_multiplier": cast(int, row["base_exp_multiplier"]),
                    "temp_exp_multiplier": row.get("temp_exp_multiplier"),
                    "base_coins_multiplier": cast(int, row["base_coins_multiplier"]),
                    "temp_coins_multiplier": row.get("temp_coins_multiplier"),
                    "base_battlepass_multiplier": cast(int, row["base_battlepass_multiplier"]),
                    "temp_battlepass_multiplier": row.get("temp_battlepass_multiplier"),
                },
            )
            migrated_multiplier_rows += 1
        except Exception:
            continue

    if migrated_multiplier_rows:
        print(f"Migrated {migrated_multiplier_rows} guild multipliers rows")

    op.create_table('guildproposalsconfig',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('create_proposal_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('proposals_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_table('guildrolerequestconfig',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('check_role_requests_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_table('guildrulesconfig',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('rules_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    connection = op.get_bind()
    op.create_table('guildbonusrole',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guildlevelsconfig.guild_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'role_id', name='uq_bonus_guild_role', deferrable=True, initially="DEFERRED")
    )
    op.create_table('guildclanshopitem',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guildclansconfig.guild_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'name', name='uq_guild_name', deferrable=True, initially="DEFERRED")
    )
    # === migrate clan shop items from guildclansconfig ===
    try:
        clan_rows = cast(
            list[dict[str, Any]],
            connection.execute(
                sa.text("SELECT guild_id, clan_shop_items FROM guildclansconfig")
            ).mappings().all(),
        )
    except Exception:
        clan_rows = []

    migrated_clan_shop_items = 0

    for row in clan_rows:
        gid = cast(int, row["guild_id"])
        raw_items = row.get("clan_shop_items")
        if raw_items is None:
            continue

        items = _load_json_object(raw_items)
        for name, cost in items.items():
            try:
                connection.execute(
                    sa.text(
                        "INSERT INTO guildclanshopitem (guild_id, name, cost) VALUES (:gid, :name, :cost)"
                    ),
                    {"gid": gid, "name": str(name), "cost": int(cast(int | str, cost))},
                )
                migrated_clan_shop_items += 1
            except Exception:
                continue

    if migrated_clan_shop_items:
        print(f"Migrated {migrated_clan_shop_items} clan shop items")

    op.create_table('guildeconomyshopitem',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guildeconomyconfig.guild_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'name', name='uq_economy_guild_name', deferrable=True, initially="DEFERRED")
    )
    # === migrate economy shop items from guildeconomyconfig ===
    try:
        economy_rows = cast(
            list[dict[str, Any]],
            connection.execute(
                sa.text("SELECT guild_id, economy_shop_items FROM guildeconomyconfig")
            ).mappings().all(),
        )
    except Exception:
        economy_rows = []

    migrated_economy_shop_items = 0

    for row in economy_rows:
        gid = cast(int, row["guild_id"])
        raw_items = row.get("economy_shop_items")
        if raw_items is None:
            continue

        items = _load_json_object(raw_items)
        for name, cost in items.items():
            try:
                connection.execute(
                    sa.text(
                        "INSERT INTO guildeconomyshopitem (guild_id, name, cost) VALUES (:gid, :name, :cost)"
                    ),
                    {"gid": gid, "name": str(name), "cost": int(cast(int | str, cost))},
                )
                migrated_economy_shop_items += 1
            except Exception:
                continue

    if migrated_economy_shop_items:
        print(f"Migrated {migrated_economy_shop_items} economy shop items")

    op.create_table('guildfractionrole',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('access_roles', sa.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guildmoderationconfig.guild_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'role_id', name='uq_fraction_guild_role', deferrable=True, initially="DEFERRED")
    )
    op.create_table('guildlevel',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guildlevelsconfig.guild_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'level', name='uq_level_guild_level', deferrable=True, initially="DEFERRED")
    )
    # === migrate level and bonus role mappings from guildlevelsconfig ===
    connection = op.get_bind()
    try:
        level_rows = cast(
            list[dict[str, Any]],
            connection.execute(
                sa.text("SELECT guild_id, level_roles, bonus_access_roles_ids FROM guildlevelsconfig")
            ).mappings().all(),
        )
    except Exception:
        level_rows = []

    migrated_level_roles = 0
    migrated_bonus_roles = 0

    for row in level_rows:
        gid = cast(int, row["guild_id"])

        # migrate level -> role mappings
        raw_level_roles = row.get("level_roles")
        if raw_level_roles is not None:
            level_roles = _load_json_object(raw_level_roles)

            for level_str, role_id in level_roles.items():
                try:
                    level_value = int(level_str)
                    connection.execute(
                        sa.text(
                            "INSERT INTO guildlevel (guild_id, level, role_id) VALUES (:gid, :level, :role_id)"
                        ),
                        {"gid": gid, "level": level_value, "role_id": int(cast(int | str, role_id))},
                    )
                    migrated_level_roles += 1
                except Exception:
                    continue

        # migrate bonus role -> coins mappings
        raw_bonus_roles = row.get("bonus_access_roles_ids")
        if raw_bonus_roles is not None:
            bonus_roles = _load_json_object(raw_bonus_roles)

            for role_id_str, coins in bonus_roles.items():
                try:
                    role_id = int(role_id_str)
                    connection.execute(
                        sa.text(
                            "INSERT INTO guildbonusrole (guild_id, role_id, coins) VALUES (:gid, :role_id, :coins)"
                        ),
                        {"gid": gid, "role_id": role_id, "coins": int(cast(int | str, coins))},
                    )
                    migrated_bonus_roles += 1
                except Exception:
                    continue

    if migrated_level_roles or migrated_bonus_roles:
        print(
            f"Migrated {migrated_level_roles} level roles and {migrated_bonus_roles} bonus roles"
        )

    op.create_table('guildorganizationalrole',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('illegal', 'legal', name='organizationalroletypeenum', native_enum=False), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guildrolerequestconfig.guild_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'role_id', name='uq_org_guild_role', deferrable=True, initially="DEFERRED",))

    # === migrate organizational and illegal roles from mainguildconfig ===
    try:
        role_rows = cast(
            list[dict[str, Any]],
            connection.execute(
                sa.text("SELECT guild_id, organizational_roles, illegal_roles FROM mainguildconfig")
            ).mappings().all(),
        )
    except Exception:
        role_rows = []

    migrated_org_roles = 0
    migrated_illegal_roles = 0

    for row in role_rows:
        gid = cast(int, row["guild_id"])

        try:
            connection.execute(
                sa.text(
                    "INSERT INTO guildrolerequestconfig (guild_id) VALUES (:gid) ON CONFLICT (guild_id) DO NOTHING"
                ),
                {"gid": gid},
            )
        except Exception:
            continue

        def _migrate_role_map(raw_value: Any, role_type: str) -> int:
            migrated = 0
            payload = _load_json_object(raw_value)
            if not payload:
                return migrated

            for tag, item in payload.items():
                if not isinstance(item, dict):
                    continue

                item_dict = cast(dict[str, Any], item)
                role_name = item_dict.get("name")
                role_id = item_dict.get("role_id")
                if role_name is None or role_id is None:
                    continue

                try:
                    connection.execute(
                        sa.text(
                            "INSERT INTO guildorganizationalrole (guild_id, role_id, name, tag, type) "
                            "VALUES (:gid, :role_id, :name, :tag, :type)"
                        ),
                        {
                            "gid": gid,
                            "role_id": int(cast(int | str, role_id)),
                            "name": str(role_name),
                            "tag": str(tag),
                            "type": role_type,
                        },
                    )
                    migrated += 1
                except Exception:
                    continue

            return migrated

        migrated_org_roles += _migrate_role_map(row.get("organizational_roles"), "legal")
        migrated_illegal_roles += _migrate_role_map(row.get("illegal_roles"), "illegal")

    if migrated_org_roles or migrated_illegal_roles:
        print(
            f"Migrated {migrated_org_roles} organizational roles and {migrated_illegal_roles} illegal roles"
        )

    op.create_table('guildrules',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guildrulesconfig.guild_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', name='uq_guild', deferrable=True, initially="DEFERRED",))
    op.create_table('guildruleschapter',
    sa.Column('rules_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['rules_id'], ['guildrules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guildrulesrule',
    sa.Column('chapter_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['guildruleschapter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guildrulessubrule',
    sa.Column('rule_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['guildrulesrule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # === migrate JSON rules from mainguildconfig into new tables ===
    connection = op.get_bind()
    try:
        rows = cast(
            list[dict[str, Any]],
            connection.execute(
                sa.text("SELECT guild_id, guild_rules, rules_channel_id FROM mainguildconfig")
            ).mappings().all(),
        )
    except Exception:
        rows = []

    imported = 0
    for row in rows:
        gid = cast(int, row["guild_id"])
        raw = row.get("guild_rules")
        if raw is None:
            continue

        data = _load_json_object(raw)

        chapters = cast(list[dict[str, Any]], data.get("chapters") or [])
        if not chapters:
            continue

        # insert or update guildrulesconfig and preserve rules_channel_id
        try:
            rcid = row.get("rules_channel_id")
            if rcid is None:
                connection.execute(
                    sa.text(
                        "INSERT INTO guildrulesconfig (guild_id) VALUES (:gid) ON CONFLICT (guild_id) DO NOTHING"
                    ),
                    {"gid": gid},
                )
            else:
                connection.execute(
                    sa.text(
                        "INSERT INTO guildrulesconfig (guild_id, rules_channel_id) VALUES (:gid, :rcid) "
                        "ON CONFLICT (guild_id) DO UPDATE SET rules_channel_id = EXCLUDED.rules_channel_id"
                    ),
                    {"gid": gid, "rcid": rcid},
                )
        except Exception:
            continue

        # create guildrules row
        try:
            res = connection.execute(
                sa.text("INSERT INTO guildrules (guild_id) VALUES (:gid) RETURNING id"),
                {"gid": gid},
            )
            rules_row = res.fetchone()
            if rules_row is None:
                continue
            rules_id = rules_row[0]
        except Exception:
            continue

        for ch in chapters:
            ch_text = str(ch.get("title") or ch.get("text") or "")
            try:
                res_ch = connection.execute(
                    sa.text(
                        "INSERT INTO guildruleschapter (rules_id, text) VALUES (:rid, :text) RETURNING id"
                    ),
                    {"rid": rules_id, "text": ch_text},
                )
                ch_row = res_ch.fetchone()
                if ch_row is None:
                    continue
                ch_id = ch_row[0]
            except Exception:
                continue

            rules = cast(list[dict[str, Any]], ch.get("rules") or [])
            for r in rules:
                r_text = str(r.get("text") or "")
                try:
                    res_r = connection.execute(
                        sa.text(
                            "INSERT INTO guildrulesrule (chapter_id, text) VALUES (:cid, :text) RETURNING id"
                        ),
                        {"cid": ch_id, "text": r_text},
                    )
                    r_row = res_r.fetchone()
                    if r_row is None:
                        continue
                    r_id = r_row[0]
                except Exception:
                    continue

                subrules = cast(list[dict[str, Any]], r.get("subrules") or [])
                for s in subrules:
                    s_text = str(s.get("text") or "")
                    try:
                        connection.execute(
                            sa.text(
                                "INSERT INTO guildrulessubrule (rule_id, text) VALUES (:rid, :text)"
                            ),
                            {"rid": r_id, "text": s_text},
                        )
                    except Exception:
                        continue

        imported += 1

    if imported:
        print(f"Imported rules for {imported} guild(s)")

    # end migration block
    op.drop_table('mainguildconfig')
    op.drop_table('guildmetaconfig')
    op.drop_column('guildclansconfig', 'clan_shop_items')
    op.drop_column('guildeconomyconfig', 'economy_shop_items')
    op.add_column('guildforumconfig', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('guildforumconfig', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('guildforumconfig', 'channel_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('guildforumconfig', 'role_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(op.f('guildforumconfig_prefix_id_key'), 'guildforumconfig', type_='unique')
    op.drop_column('guildforumconfig', 'prefix_id')
    op.alter_column('guildlevelsconfig', 'count_messages_type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'channel_only'::character varying"))
    op.drop_column('guildlevelsconfig', 'temp_battlepass_multiplier')
    op.drop_column('guildlevelsconfig', 'base_coins_multiplier')
    op.drop_column('guildlevelsconfig', 'base_battlepass_multiplier')
    op.drop_column('guildlevelsconfig', 'base_exp_multiplier')
    op.drop_column('guildlevelsconfig', 'temp_exp_multiplier')
    op.drop_column('guildlevelsconfig', 'bonus_access_roles_ids')
    op.drop_column('guildlevelsconfig', 'temp_coins_multiplier')
    op.drop_column('guildlevelsconfig', 'level_roles')
    op.alter_column('guildmoderationconfig', 'mute_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('guildmoderationconfig', 'fraction_roles_access_roles_ids')
    op.drop_column('guildmoderationconfig', 'inactive_channel_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guildmoderationconfig', sa.Column('inactive_channel_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('guildmoderationconfig', sa.Column('fraction_roles_access_roles_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.alter_column('guildmoderationconfig', 'mute_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('guildlevelsconfig', sa.Column('level_roles', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False))
    op.add_column('guildlevelsconfig', sa.Column('temp_coins_multiplier', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('guildlevelsconfig', sa.Column('bonus_access_roles_ids', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False))
    op.add_column('guildlevelsconfig', sa.Column('temp_exp_multiplier', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('guildlevelsconfig', sa.Column('base_exp_multiplier', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('guildlevelsconfig', sa.Column('base_battlepass_multiplier', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.add_column('guildlevelsconfig', sa.Column('base_coins_multiplier', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('guildlevelsconfig', sa.Column('temp_battlepass_multiplier', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('guildlevelsconfig', 'count_messages_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'channel_only'::character varying"))
    op.add_column('guildforumconfig', sa.Column('prefix_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('guildforumconfig_prefix_id_key'), 'guildforumconfig', ['prefix_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('guildforumconfig', 'role_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('guildforumconfig', 'channel_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('guildforumconfig', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('guildforumconfig', 'is_active')
    op.add_column('guildeconomyconfig', sa.Column('economy_shop_items', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False))
    op.add_column('guildclansconfig', sa.Column('clan_shop_items', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.create_table('guildmetaconfig',
    sa.Column('guild_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('other_config_access_roles_ids', postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=True),
    sa.Column('logging_config_access_roles_ids', postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=True),
    sa.Column('economy_config_access_roles_ids', postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=True),
    sa.Column('levels_config_access_roles_ids', postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=True),
    sa.Column('clans_config_access_roles_ids', postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=True),
    sa.Column('private_channels_config_access_roles_ids', postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=True),
    sa.Column('moderation_config_access_roles_ids', postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=True),
    sa.Column('notifications_config_access_roles_ids', postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=True),
    sa.Column('infomaker_config_access_roles_ids', postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('guildmetaconfig_pkey')),
    sa.UniqueConstraint('guild_id', name=op.f('guildmetaconfig_guild_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('mainguildconfig',
    sa.Column('guild_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('rules_channel_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('create_proposal_channel_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('proposals_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('illegal_roles', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False),
    sa.Column('organizational_roles', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('voice_temp_roles', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('faq', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('check_role_requests_channel_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('guild_rules', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text('\'{"chapters": []}\'::json'), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('mainguildconfig_pkey')),
    sa.UniqueConstraint('guild_id', name=op.f('mainguildconfig_guild_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('guildrulessubrule')
    op.drop_table('guildrulesrule')
    op.drop_table('guildruleschapter')
    op.drop_table('guildrules')
    op.drop_table('guildorganizationalrole')
    op.drop_table('guildlevel')
    op.drop_table('guildfractionrole')
    op.drop_table('guildeconomyshopitem')
    op.drop_table('guildclanshopitem')
    op.drop_table('guildbonusrole')
    op.drop_table('guildrulesconfig')
    op.drop_table('guildrolerequestconfig')
    op.drop_table('guildproposalsconfig')
    op.drop_table('guildmultipliersconfig')
    op.drop_table('guildfaqconfig')
    op.drop_table('guildaccessconfig')
    # ### end Alembic commands ###
