""" change fractionroleconfig

Revision ID: b0304e52bb0d
Revises: 2c78daa4fc1a
Create Date: 2025-11-10 19:14:17.636598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0304e52bb0d'
down_revision: Union[str, Sequence[str], None] = '2c78daa4fc1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guildeconomyconfig', 'economy_shop_channel_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guildeconomyconfig', sa.Column('economy_shop_channel_id', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
