"""Mon Oct 20 08:29:35 PM CEST 2025

Revision ID: b1cbe8459b83
Revises: 5492e9e0eb7f
Create Date: 2025-10-20 20:29:36.450727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1cbe8459b83'
down_revision: Union[str, Sequence[str], None] = '5492e9e0eb7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clanmember', sa.Column('guild_id', sa.BigInteger(), nullable=False))
    op.add_column('clanmember', sa.Column('user_ref_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_clanmember_user_ref_id'), 'clanmember', ['user_ref_id'], unique=True)
    op.create_foreign_key(None, 'clanmember', 'user', ['user_ref_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clanmember', type_='foreignkey')
    op.drop_index(op.f('ix_clanmember_user_ref_id'), table_name='clanmember')
    op.drop_column('clanmember', 'user_ref_id')
    op.drop_column('clanmember', 'guild_id')
    # ### end Alembic commands ###
