"""add_temp_valentines

Revision ID: b30dc2cbfbe0
Revises: 388dd26ece6a
Create Date: 2026-02-07 19:31:30.786305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b30dc2cbfbe0'
down_revision: Union[str, Sequence[str], None] = '388dd26ece6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('battlepasslevel')
    op.add_column('user', sa.Column('sended_valentines', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('user', sa.Column('received_valentines', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'received_valentines')
    op.drop_column('user', 'sended_valentines')
    op.create_table('battlepasslevel',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exp_required', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reward', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('battlepasslevel_pkey')),
    sa.UniqueConstraint('level', 'guild_id', name=op.f('ux_level_guild_battlepasslevel'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
