"""add_temp_valentines

Revision ID: b30dc2cbfbe0
Revises: 388dd26ece6a
Create Date: 2026-02-07 19:31:30.786305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b30dc2cbfbe0'
down_revision: Union[str, Sequence[str], None] = '388dd26ece6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sended_valentines', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('user', sa.Column('received_valentines', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'received_valentines')
    op.drop_column('user', 'sended_valentines')
    # ### end Alembic commands ###
