"""refactor_indexes

Revision ID: b4c4cf46f50d
Revises: 1e91b387214b
Create Date: 2026-02-22 15:29:24.014508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4c4cf46f50d'
down_revision: Union[str, Sequence[str], None] = '1e91b387214b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_casinobet_user_id'), table_name='casinobet')
    op.create_index('ix_casino_bet_user_game', 'casinobet', ['user_id', 'game_id'], unique=False)
    op.create_index('ix_casino_game_guild_message', 'casinogame', ['guild_id', 'message_id'], unique=False)
    op.create_index('ix_casino_game_guild_state_endtime', 'casinogame', ['guild_id', 'state', 'end_time'], unique=False)
    op.drop_index(op.f('ix_clanmember_user_id'), table_name='clanmember')
    op.create_index('ix_transfer_guild_receiver_created', 'transferhistory', ['guild_id', 'receiver_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_transfer_guild_sender_created', 'transferhistory', ['guild_id', 'user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_user_guild_battlepass', 'user', ['guild_id', sa.literal_column('battle_pass_level DESC')], unique=False)
    op.create_index('ix_user_guild_coins', 'user', ['guild_id', sa.literal_column('coins DESC')], unique=False)
    op.create_index('ix_user_guild_level_exp', 'user', ['guild_id', sa.literal_column('level DESC'), sa.literal_column('current_exp DESC')], unique=False)
    op.create_index('ix_user_guild_messages', 'user', ['guild_id', sa.literal_column('messages_count DESC')], unique=False)
    op.create_index('ix_user_guild_voice', 'user', ['guild_id', sa.literal_column('voice_activity DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_guild_voice', table_name='user')
    op.drop_index('ix_user_guild_messages', table_name='user')
    op.drop_index('ix_user_guild_level_exp', table_name='user')
    op.drop_index('ix_user_guild_coins', table_name='user')
    op.drop_index('ix_user_guild_battlepass', table_name='user')
    op.drop_index('ix_transfer_guild_sender_created', table_name='transferhistory')
    op.drop_index('ix_transfer_guild_receiver_created', table_name='transferhistory')
    op.create_index(op.f('ix_clanmember_user_id'), 'clanmember', ['user_id'], unique=False)
    op.drop_index('ix_casino_game_guild_state_endtime', table_name='casinogame')
    op.drop_index('ix_casino_game_guild_message', table_name='casinogame')
    op.drop_index('ix_casino_bet_user_game', table_name='casinobet')
    op.create_index(op.f('ix_casinobet_user_id'), 'casinobet', ['user_id'], unique=False)
    # ### end Alembic commands ###
