"""Tue Oct 14 10:08:40 PM CEST 2025

Revision ID: b9a573bf4261
Revises: 4eba63d7d3d6
Create Date: 2025-10-14 22:08:47.134902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9a573bf4261'
down_revision: Union[str, Sequence[str], None] = '4eba63d7d3d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('COMMIT')  # Завершити поточну транзакцію
    op.create_table('notifystate',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('moderator_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.Enum('pending', 'timed_out', name='notifystateenum', native_enum=False), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notify_guild_user_updated_desc', 'notifystate', ['guild_id', 'user_id', sa.literal_column('updated_at DESC')], unique=False, postgresql_concurrently=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_notify_guild_user_updated_desc', table_name='notifystate', postgresql_concurrently=True)
    op.drop_table('notifystate')
    # ### end Alembic commands ###
