"""Revision (Wed Aug 19 16:13:29 CEST 2026)

Revision ID: bbd438c928b3
Revises: 3e650f60e04b
Create Date: 2026-08-19 16:13:29.852534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd438c928b3'
down_revision: Union[str, Sequence[str], None] = '3e650f60e04b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discordwebhook',
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loggingrevision',
    sa.Column('revision_id', sa.String(), nullable=False),
    sa.Column('down_revision_id', sa.String(), nullable=True),
    sa.Column('config_type', sa.Enum('forum', 'logging', 'economy', 'levels', 'clans', 'private_channels', 'moderation', 'notifications', 'infomakers', 'rules', 'proposals', 'role_request', 'multiplers', 'tickets', 'access', name='configtypeenum', native_enum=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('old_data', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('new_data', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('revision_id')
    )
    op.create_index('ix_logging_revision_guild_config_created', 'loggingrevision', ['guild_id', 'config_type', 'created_at'], unique=False)
    op.add_column('guildclansconfig', sa.Column('clan_payday_webhook_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'guildclansconfig', 'discordwebhook', ['clan_payday_webhook_id'], ['id'], ondelete='SET NULL')
    op.drop_column('guildclansconfig', 'clan_payday_channel_id')
    op.add_column('guildforumconfig', sa.Column('notify_webhook_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('guildforumconfig_channel_id_key'), 'guildforumconfig', type_='unique')
    op.create_foreign_key(None, 'guildforumconfig', 'discordwebhook', ['notify_webhook_id'], ['id'], ondelete='SET NULL')
    op.drop_column('guildforumconfig', 'channel_id')
    op.add_column('guildinfomakerconfig', sa.Column('admins_roles_logging_webhook_id', sa.Integer(), nullable=True))
    op.add_column('guildinfomakerconfig', sa.Column('leaders_roles_logging_webhook_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'guildinfomakerconfig', 'discordwebhook', ['admins_roles_logging_webhook_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'guildinfomakerconfig', 'discordwebhook', ['leaders_roles_logging_webhook_id'], ['id'], ondelete='SET NULL')
    op.drop_column('guildinfomakerconfig', 'admins_roles_logging_channel_id')
    op.drop_column('guildinfomakerconfig', 'leaders_roles_logging_channel_id')
    op.add_column('guildlevelsconfig', sa.Column('level_notify_webhook_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'guildlevelsconfig', 'discordwebhook', ['level_notify_webhook_id'], ['id'], ondelete='SET NULL')
    op.drop_column('guildlevelsconfig', 'level_notify_channel_id')
    op.add_column('guildloggingconfig', sa.Column('bans_log_webhook_id', sa.Integer(), nullable=True))
    op.add_column('guildloggingconfig', sa.Column('clans_log_webhook_id', sa.Integer(), nullable=True))
    op.add_column('guildloggingconfig', sa.Column('members_log_webhook_id', sa.Integer(), nullable=True))
    op.add_column('guildloggingconfig', sa.Column('messages_log_webhook_id', sa.Integer(), nullable=True))
    op.add_column('guildloggingconfig', sa.Column('voices_log_webhook_id', sa.Integer(), nullable=True))
    op.add_column('guildloggingconfig', sa.Column('moderation_log_webhook_id', sa.Integer(), nullable=True))
    op.add_column('guildloggingconfig', sa.Column('tickets_log_webhook_id', sa.Integer(), nullable=True))
    op.add_column('guildloggingconfig', sa.Column('roles_log_webhook_id', sa.Integer(), nullable=True))
    op.add_column('guildloggingconfig', sa.Column('channels_log_webhook_id', sa.Integer(), nullable=True))
    op.add_column('guildloggingconfig', sa.Column('reactions_log_webhook_id', sa.Integer(), nullable=True))
    op.add_column('guildloggingconfig', sa.Column('private_rooms_log_webhook_id', sa.Integer(), nullable=True))
    op.add_column('guildloggingconfig', sa.Column('economy_log_webhook_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'guildloggingconfig', 'discordwebhook', ['members_log_webhook_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'guildloggingconfig', 'discordwebhook', ['private_rooms_log_webhook_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'guildloggingconfig', 'discordwebhook', ['moderation_log_webhook_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'guildloggingconfig', 'discordwebhook', ['bans_log_webhook_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'guildloggingconfig', 'discordwebhook', ['messages_log_webhook_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'guildloggingconfig', 'discordwebhook', ['reactions_log_webhook_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'guildloggingconfig', 'discordwebhook', ['channels_log_webhook_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'guildloggingconfig', 'discordwebhook', ['voices_log_webhook_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'guildloggingconfig', 'discordwebhook', ['roles_log_webhook_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'guildloggingconfig', 'discordwebhook', ['clans_log_webhook_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'guildloggingconfig', 'discordwebhook', ['economy_log_webhook_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'guildloggingconfig', 'discordwebhook', ['tickets_log_webhook_id'], ['id'], ondelete='SET NULL')
    op.drop_column('guildloggingconfig', 'clans_log_channel_id')
    op.drop_column('guildloggingconfig', 'economy_log_channel_id')
    op.drop_column('guildloggingconfig', 'roles_log_channel_id')
    op.drop_column('guildloggingconfig', 'voices_log_channel_id')
    op.drop_column('guildloggingconfig', 'channels_log_channel_id')
    op.drop_column('guildloggingconfig', 'reactions_log_channel_id')
    op.drop_column('guildloggingconfig', 'tickets_log_channel_id')
    op.drop_column('guildloggingconfig', 'messages_log_channel_id')
    op.drop_column('guildloggingconfig', 'private_rooms_log_channel_id')
    op.drop_column('guildloggingconfig', 'bans_log_channel_id')
    op.drop_column('guildloggingconfig', 'moderation_log_channel_id')
    op.drop_column('guildloggingconfig', 'members_log_channel_id')
    op.add_column('guildnotificationsconfig', sa.Column('notifications_for_moderation_webhook_id', sa.Integer(), nullable=True))
    op.add_column('guildnotificationsconfig', sa.Column('notifications_from_bot_webhook_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'guildnotificationsconfig', 'discordwebhook', ['notifications_from_bot_webhook_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'guildnotificationsconfig', 'discordwebhook', ['notifications_for_moderation_webhook_id'], ['id'], ondelete='SET NULL')
    op.drop_column('guildnotificationsconfig', 'notifications_for_moderation_channel_id')
    op.drop_column('guildnotificationsconfig', 'notifications_from_bot_channel_id')
    op.add_column('guildrulesconfig', sa.Column('economy_log_webhook_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'guildrulesconfig', 'discordwebhook', ['economy_log_webhook_id'], ['id'], ondelete='SET NULL')
    op.drop_column('guildrulesconfig', 'rules_channel_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guildrulesconfig', sa.Column('rules_channel_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'guildrulesconfig', type_='foreignkey')
    op.drop_column('guildrulesconfig', 'economy_log_webhook_id')
    op.add_column('guildnotificationsconfig', sa.Column('notifications_from_bot_channel_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('guildnotificationsconfig', sa.Column('notifications_for_moderation_channel_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'guildnotificationsconfig', type_='foreignkey')
    op.drop_constraint(None, 'guildnotificationsconfig', type_='foreignkey')
    op.drop_column('guildnotificationsconfig', 'notifications_from_bot_webhook_id')
    op.drop_column('guildnotificationsconfig', 'notifications_for_moderation_webhook_id')
    op.add_column('guildloggingconfig', sa.Column('members_log_channel_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('guildloggingconfig', sa.Column('moderation_log_channel_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('guildloggingconfig', sa.Column('bans_log_channel_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('guildloggingconfig', sa.Column('private_rooms_log_channel_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('guildloggingconfig', sa.Column('messages_log_channel_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('guildloggingconfig', sa.Column('tickets_log_channel_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('guildloggingconfig', sa.Column('reactions_log_channel_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('guildloggingconfig', sa.Column('channels_log_channel_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('guildloggingconfig', sa.Column('voices_log_channel_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('guildloggingconfig', sa.Column('roles_log_channel_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('guildloggingconfig', sa.Column('economy_log_channel_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('guildloggingconfig', sa.Column('clans_log_channel_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'guildloggingconfig', type_='foreignkey')
    op.drop_constraint(None, 'guildloggingconfig', type_='foreignkey')
    op.drop_constraint(None, 'guildloggingconfig', type_='foreignkey')
    op.drop_constraint(None, 'guildloggingconfig', type_='foreignkey')
    op.drop_constraint(None, 'guildloggingconfig', type_='foreignkey')
    op.drop_constraint(None, 'guildloggingconfig', type_='foreignkey')
    op.drop_constraint(None, 'guildloggingconfig', type_='foreignkey')
    op.drop_constraint(None, 'guildloggingconfig', type_='foreignkey')
    op.drop_constraint(None, 'guildloggingconfig', type_='foreignkey')
    op.drop_constraint(None, 'guildloggingconfig', type_='foreignkey')
    op.drop_constraint(None, 'guildloggingconfig', type_='foreignkey')
    op.drop_constraint(None, 'guildloggingconfig', type_='foreignkey')
    op.drop_column('guildloggingconfig', 'economy_log_webhook_id')
    op.drop_column('guildloggingconfig', 'private_rooms_log_webhook_id')
    op.drop_column('guildloggingconfig', 'reactions_log_webhook_id')
    op.drop_column('guildloggingconfig', 'channels_log_webhook_id')
    op.drop_column('guildloggingconfig', 'roles_log_webhook_id')
    op.drop_column('guildloggingconfig', 'tickets_log_webhook_id')
    op.drop_column('guildloggingconfig', 'moderation_log_webhook_id')
    op.drop_column('guildloggingconfig', 'voices_log_webhook_id')
    op.drop_column('guildloggingconfig', 'messages_log_webhook_id')
    op.drop_column('guildloggingconfig', 'members_log_webhook_id')
    op.drop_column('guildloggingconfig', 'clans_log_webhook_id')
    op.drop_column('guildloggingconfig', 'bans_log_webhook_id')
    op.add_column('guildlevelsconfig', sa.Column('level_notify_channel_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'guildlevelsconfig', type_='foreignkey')
    op.drop_column('guildlevelsconfig', 'level_notify_webhook_id')
    op.add_column('guildinfomakerconfig', sa.Column('leaders_roles_logging_channel_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('guildinfomakerconfig', sa.Column('admins_roles_logging_channel_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'guildinfomakerconfig', type_='foreignkey')
    op.drop_constraint(None, 'guildinfomakerconfig', type_='foreignkey')
    op.drop_column('guildinfomakerconfig', 'leaders_roles_logging_webhook_id')
    op.drop_column('guildinfomakerconfig', 'admins_roles_logging_webhook_id')
    op.add_column('guildforumconfig', sa.Column('channel_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'guildforumconfig', type_='foreignkey')
    op.create_unique_constraint(op.f('guildforumconfig_channel_id_key'), 'guildforumconfig', ['channel_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('guildforumconfig', 'notify_webhook_id')
    op.add_column('guildclansconfig', sa.Column('clan_payday_channel_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'guildclansconfig', type_='foreignkey')
    op.drop_column('guildclansconfig', 'clan_payday_webhook_id')
    op.drop_index('ix_logging_revision_guild_config_created', table_name='loggingrevision')
    op.drop_table('loggingrevision')
    op.drop_table('discordwebhook')
    # ### end Alembic commands ###
