"""guild/global badges system

Revision ID: bc06aaa66425
Revises: a301b75257bc
Create Date: 2026-10-04 20:46:21.223967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc06aaa66425'
down_revision: Union[str, Sequence[str], None] = 'a301b75257bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('globalbadge',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('emoji_str', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='ux_global_badge_name')
    )
    op.create_table('guildbadge',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('emoji_str', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'name', name='ux_guild_badge_name')
    )
    op.create_table('userglobalbadge',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['globalbadge.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_id', name='ux_user_global_badge')
    )
    op.create_table('userguildbadge',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['guildbadge.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'guild_id'], ['user.id', 'user.guild_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guild_id', 'user_id', 'id'),
    sa.UniqueConstraint('badge_id', 'user_id', 'guild_id', name='ux_user_guild_badge')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userguildbadge')
    op.drop_table('userglobalbadge')
    op.drop_table('guildbadge')
    op.drop_table('globalbadge')
    # ### end Alembic commands ###
