"""add_new_economy_tables

Revision ID: bc10cf97b36d
Revises: 7fedbff7e42f
Create Date: 2026-01-23 23:33:37.839947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc10cf97b36d'
down_revision: Union[str, Sequence[str], None] = '7fedbff7e42f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('drop', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'name', name='ux_name_guild_case')
    )
    op.create_table('color',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'role_id', name='ux_role_guild_color')
    )
    op.create_table('user_colors',
        sa.Column('guild_id', sa.BigInteger(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('color_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['color_id'], ['color.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['guild_id', 'user_id'], ['user.guild_id', 'user.user_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id', 'color_id', 'guild_id')
    )
    op.create_table('usercase',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('guild_id', sa.BigInteger(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('case_id', sa.Integer(), nullable=False),
        sa.Column('amount', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['guild_id', 'user_id'], ['user.guild_id', 'user.user_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('guild_id', 'user_id', 'case_id'),
        sa.UniqueConstraint('case_id', 'user_id', 'guild_id', name='ux_user_case_guild_user')
    )
    op.create_table("battlepasslevel",
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('guild_id', sa.BigInteger(), nullable=False),
        sa.Column('level', sa.Integer(), nullable=False),
        sa.Column('exp_required', sa.Integer(), nullable=False),
        sa.Column('reward', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
        sa.UniqueConstraint("level", "guild_id",  name='ux_level_guild_battlepasslevel')
    )
    op.drop_column('guildeconomyconfig', 'drop_from_coins_case')
    op.drop_column('guildeconomyconfig', 'battlepass_rewards')
    op.drop_column('guildeconomyconfig', 'colors')
    op.drop_column('guildeconomyconfig', 'drop_from_colors_case')
    op.drop_column('user', 'inventory')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('inventory', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text('\'{"cases": {}, "colors": []}\'::json'), autoincrement=False, nullable=False))
    op.add_column('guildeconomyconfig', sa.Column('drop_from_colors_case', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False))
    op.add_column('guildeconomyconfig', sa.Column('colors', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False))
    op.add_column('guildeconomyconfig', sa.Column('battlepass_rewards', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False))
    op.add_column('guildeconomyconfig', sa.Column('drop_from_coins_case', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False))
    op.drop_table('usercase')
    op.drop_table('user_colors')
    op.drop_table('color')
    op.drop_table('case')
    # ### end Alembic commands ###
