"""Wed Oct 15 04:51:41 PM CEST 2025

Revision ID: bcb6e1604b55
Revises: b9a573bf4261
Create Date: 2025-10-15 16:51:49.094310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bcb6e1604b55'
down_revision: Union[str, Sequence[str], None] = 'b9a573bf4261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('COMMIT')
    op.add_column('notifystate', sa.Column('end_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('idx_notify_guild_user_updated_desc'), table_name='notifystate')
    op.create_index('idx_notify_guild_user_end_time_desc', 'notifystate', ['guild_id', 'user_id', sa.literal_column('end_time DESC')], unique=False, postgresql_concurrently=True)
    op.drop_column('notifystate', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifystate', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index('idx_notify_guild_user_end_time_desc', table_name='notifystate', postgresql_concurrently=True)
    op.create_index(op.f('idx_notify_guild_user_updated_desc'), 'notifystate', ['guild_id', 'user_id', sa.literal_column('updated_at DESC')], unique=False)
    op.drop_column('notifystate', 'end_time')
    # ### end Alembic commands ###
