"""add inactive

Revision ID: bf9f99318dee
Revises: 75925089facf
Create Date: 2026-05-19 15:54:20.497041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf9f99318dee'
down_revision: Union[str, Sequence[str], None] = '75925089facf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guildforumconfig', sa.Column('prefix_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_guild_channel_role_section'), 'guildforumconfig', type_='unique')
    op.create_unique_constraint(None, 'guildforumconfig', ['role_id'])
    op.create_unique_constraint(None, 'guildforumconfig', ['section_id'])
    op.create_unique_constraint(None, 'guildforumconfig', ['guild_id'])
    op.create_unique_constraint(None, 'guildforumconfig', ['channel_id'])
    op.create_unique_constraint(None, 'guildforumconfig', ['prefix_id'])
    op.add_column('guildmoderationconfig', sa.Column('inactive_channel_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'processedforumthread', ['thread_id'])
    # ### end Alembic commands ###

    # Insert prefix_id values for guilds
    op.execute(
        "UPDATE guildforumconfig SET prefix_id = 104 WHERE guild_id = 1036712610919370834"
    )
    op.execute(
        "UPDATE guildforumconfig SET prefix_id = 113 WHERE guild_id = 693824534163488838"
    )
    op.execute(
        "UPDATE guildforumconfig SET prefix_id = 94 WHERE guild_id = 952303456222318693"
    )
    op.execute(
        "UPDATE guildforumconfig SET prefix_id = 103 WHERE guild_id = 347728316557426688"
    )
    op.execute(
        "UPDATE guildforumconfig SET prefix_id = 65 WHERE guild_id = 969305296558235678"
    )

    # Make prefix_id NOT NULL
    op.alter_column('guildforumconfig', 'prefix_id',
                    existing_type=sa.Integer(),
                    nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # Make prefix_id nullable before dropping
    op.alter_column('guildforumconfig', 'prefix_id',
                    existing_type=sa.Integer(),
                    nullable=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'processedforumthread', type_='unique')
    op.drop_column('guildmoderationconfig', 'inactive_channel_id')
    op.drop_constraint(None, 'guildforumconfig', type_='unique')
    op.drop_constraint(None, 'guildforumconfig', type_='unique')
    op.drop_constraint(None, 'guildforumconfig', type_='unique')
    op.drop_constraint(None, 'guildforumconfig', type_='unique')
    op.drop_constraint(None, 'guildforumconfig', type_='unique')
    op.create_unique_constraint(op.f('uq_guild_channel_role_section'), 'guildforumconfig', ['guild_id', 'channel_id', 'role_id', 'section_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('guildforumconfig', 'prefix_id')
    # ### end Alembic commands ###
