"""Tue Sep  2 11:55:17 PM CEST 2025

Revision ID: c36d7f070603
Revises: 8a98275fef79
Create Date: 2025-09-02 23:55:24.317242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c36d7f070603'
down_revision: Union[str, Sequence[str], None] = '8a98275fef79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temppunish',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_temp_punish_guild_user_time_now', 'temppunish', ['guild_id', 'user_id', 'end_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_temp_punish_guild_user_time_now', table_name='temppunish')
    op.drop_table('temppunish')
    # ### end Alembic commands ###
