"""bank system and vip statuses

Revision ID: cb335ac39147
Revises: 1d2e7e87b339
Create Date: 2026-09-27 15:09:44.338448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb335ac39147'
down_revision: Union[str, Sequence[str], None] = '1d2e7e87b339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vipstatus',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('emoji_str', sa.String(), nullable=True),
    sa.Column('deposit_max_balance', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('deposit_interest_rate', sa.Numeric(precision=5, scale=4), server_default=sa.text('0.0000'), nullable=False),
    sa.Column('deposit_interest_cap_amount', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('shop_discount', sa.Numeric(precision=5, scale=4), server_default=sa.text('0.0000'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'name', name='uv_guild_name_vip'),
    sa.UniqueConstraint('guild_id', 'role_id', name='ux_guild_role_vip')
    )
    op.create_table('caseopensession',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('rerolls_used', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'expired', name='caseopensessionstatus', native_enum=False), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guild_id', 'user_id'], ['user.guild_id', 'user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_caseopensession_status_expires_at', 'caseopensession', ['status', 'expires_at'], unique=False)
    op.create_table('uservipstatus',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('vip_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guild_id', 'user_id'], ['user.guild_id', 'user.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vip_id'], ['vipstatus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guild_id', 'user_id', 'id'),
    sa.UniqueConstraint('vip_id', 'user_id', 'guild_id', name='ux_user_vip_guild'),
    sa.UniqueConstraint('vip_id', 'user_id', 'is_active', name='ux_user_active_vip_guild')
    )
    op.create_index('ix_user_vip_active_guild_user', 'uservipstatus', ['guild_id', 'user_id'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_table('caseopenreward',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('reward', sa.JSON(), nullable=False),
    sa.Column('reroll_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['caseopensession.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'position', name='uq_case_open_reward_position')
    )
    op.create_index('ix_caseopenreward_session_id', 'caseopenreward', ['session_id'], unique=False)
    op.add_column('battlepasslevel', sa.Column('additional_reward', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=True))
    op.add_column('guildeconomyconfig', sa.Column('deposit_max_balance', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('guildeconomyconfig', sa.Column('deposit_base_interest_rate', sa.Numeric(precision=5, scale=4), server_default=sa.text('0.0000'), nullable=False))
    op.add_column('guildeconomyconfig', sa.Column('deposit_interest_cap_amount', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('user', sa.Column('rerolls', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('user', sa.Column('battle_pass_additional_reward_claimed_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'battle_pass_additional_reward_claimed_level')
    op.drop_column('user', 'rerolls')
    op.drop_column('guildeconomyconfig', 'deposit_interest_cap_amount')
    op.drop_column('guildeconomyconfig', 'deposit_base_interest_rate')
    op.drop_column('guildeconomyconfig', 'deposit_max_balance')
    op.drop_column('battlepasslevel', 'additional_reward')
    op.drop_index('ix_caseopenreward_session_id', table_name='caseopenreward')
    op.drop_table('caseopenreward')
    op.drop_index('ix_user_vip_active_guild_user', table_name='uservipstatus', postgresql_where=sa.text('is_active = true'))
    op.drop_table('uservipstatus')
    op.drop_index('ix_caseopensession_status_expires_at', table_name='caseopensession')
    op.drop_table('caseopensession')
    op.drop_table('vipstatus')
    # ### end Alembic commands ###
