"""Sat Aug  9 08:46:50 PM CEST 2025

Revision ID: ccebc9097877
Revises: 87fd87c2ef1b
Create Date: 2025-08-09 20:46:51.725824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccebc9097877'
down_revision: Union[str, Sequence[str], None] = '87fd87c2ef1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guildconfig', sa.Column('bans_log_channel_id', sa.BigInteger(), nullable=True))
    op.add_column('guildconfig', sa.Column('reactions_log_channel_id', sa.BigInteger(), nullable=True))
    op.drop_column('guildconfig', 'ban_log_channel_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guildconfig', sa.Column('ban_log_channel_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('guildconfig', 'reactions_log_channel_id')
    op.drop_column('guildconfig', 'bans_log_channel_id')
    # ### end Alembic commands ###
