"""Tue Oct 28 09:09:53 PM CET 2025

Revision ID: cd22d68ffa80
Revises: f98e57314a4b
Create Date: 2025-10-28 21:09:59.959284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd22d68ffa80'
down_revision: Union[str, Sequence[str], None] = 'f98e57314a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clan', 'current_exp',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('clan', 'exp_to_level',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('clan', 'level',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.add_column('guildclansconfig', sa.Column('base_exp_multiplier', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.drop_column('guildclansconfig', 'clan_reputation_per_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guildclansconfig', sa.Column('clan_reputation_per_message', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('guildclansconfig', 'base_exp_multiplier')
    op.alter_column('clan', 'level',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('clan', 'exp_to_level',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('clan', 'current_exp',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
