"""Thu Sep 25 06:20:13 PM CEST 2025

Revision ID: cd80e7f34815
Revises: 749e62e78681
Create Date: 2025-09-25 18:20:19.505536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd80e7f34815'
down_revision: Union[str, Sequence[str], None] = '749e62e78681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rolerequeststate',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('moderator_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.Enum('pending', 'requested', 'approved', 'denied', name='rolerequeststateenum', native_enum=False), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rolerequeststate')
    # ### end Alembic commands ###
