"""Mon Oct 20 07:41:16 PM CEST 2025

Revision ID: d10cf3da429b
Revises: 6243905c070e
Create Date: 2025-10-20 19:41:17.848736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd10cf3da429b'
down_revision: Union[str, Sequence[str], None] = '6243905c070e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clanmember',
    sa.Column('clan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('leader', 'deputy', 'member', name='clanmemberroleenum', native_enum=False), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['clan_id'], ['clan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clan_id', 'user_id', name='uq_clan_member')
    )
    op.create_index('ix_clan_members_clan_role', 'clanmember', ['clan_id', 'role'], unique=False)
    op.create_index('uq_one_leader_per_clan', 'clanmember', ['clan_id'], unique=True, postgresql_where=sa.text("role = 'leader'"))
    op.drop_column('clan', 'deputies')
    op.drop_column('clan', 'leader_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clan', sa.Column('leader_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('clan', sa.Column('deputies', postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=False))
    op.drop_index('uq_one_leader_per_clan', table_name='clanmember', postgresql_where=sa.text("role = 'leader'"))
    op.drop_index('ix_clan_members_clan_role', table_name='clanmember')
    op.drop_table('clanmember')
    # ### end Alembic commands ###
