"""Sun Sep 21 10:30:42 PM CEST 2025

Revision ID: d286bca02e54
Revises: 3987deacccd3
Create Date: 2025-09-21 22:30:48.599258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd286bca02e54'
down_revision: Union[str, Sequence[str], None] = '3987deacccd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticketstate', sa.Column('channel_id', sa.BigInteger(), nullable=False))
    op.alter_column('ticketstate', 'state',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('opened', 'pinned', 'closed', 'deleted', name='ticketstateenum', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticketstate', 'state',
               existing_type=sa.Enum('opened', 'pinned', 'closed', 'deleted', name='ticketstateenum', native_enum=False),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    op.drop_column('ticketstate', 'channel_id')
    # ### end Alembic commands ###
