"""Revision (Fri Aug 28 19:49:41 CEST 2026)

Revision ID: d44bc132697a
Revises: 3174585bfa7d
Create Date: 2026-08-28 19:49:41.964601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd44bc132697a'
down_revision: Union[str, Sequence[str], None] = '3174585bfa7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shoporderstate', sa.Column('payload', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shoporderstate', 'payload')
    # ### end Alembic commands ###
