"""Tue Oct  7 09:53:05 PM CEST 2025

Revision ID: d4aa02108298
Revises: 8044bf27a0f9
Create Date: 2025-10-07 21:53:09.253030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4aa02108298'
down_revision: Union[str, Sequence[str], None] = '8044bf27a0f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guildinfomakerconfig',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('admins_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('leaders_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('admins_roles_logging_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('leaders_roles_logging_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guildinfomakerconfig')
    # ### end Alembic commands ###
