""" initial structure

Revision ID: d5bfd240d0dd
Revises: 
Create Date: 2025-11-24 18:32:10.122368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5bfd240d0dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('changestat',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('moderator_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('ban', 'kick', 'mute', 'vmute', 'mpmute', 'ticketban', 'ticket', 'role_remove', 'role_accept', name='changestattypeenum', native_enum=False), nullable=False),
    sa.Column('time_now', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_changestats_guild_id_moderator_id_time_now', 'changestat', ['guild_id', 'moderator_id', 'time_now'], unique=False)
    op.create_table('clan',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('current_exp', sa.Integer(), nullable=False),
    sa.Column('exp_to_level', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('max_deputies', sa.Integer(), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('payday_multipler', sa.Integer(), nullable=False),
    sa.Column('invite_message', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'name', name='uq_clan_guild_name')
    )
    op.create_index(op.f('ix_clan_guild_id'), 'clan', ['guild_id'], unique=False)
    op.create_table('guildclansconfig',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('clan_payday_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('clan_shop_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('clan_shop_items', sa.JSON(), nullable=False),
    sa.Column('clans_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('clan_buy_ping_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('clan_reputation_per_payday', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('base_exp_multiplier', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('clan_improvements', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_table('guildeconomyconfig',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('coin_name', sa.String(), nullable=True),
    sa.Column('economy_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('reward_bonus', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('economy_shop_buy_ping_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('economy_shop_items', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=False),
    sa.Column('colors', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=False),
    sa.Column('drop_from_coins_case', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=False),
    sa.Column('drop_from_colors_case', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=False),
    sa.Column('last_roulette_games', sa.ARRAY(sa.String()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('battlepass_rewards', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_table('guildinfomakerconfig',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('admins_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('leaders_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('admins_roles_logging_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('leaders_roles_logging_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_table('guildlevelsconfig',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('count_messages_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('level_notify_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('base_exp_multiplier', sa.Integer(), nullable=False),
    sa.Column('temp_exp_multiplier', sa.Integer(), nullable=True),
    sa.Column('base_coins_multiplier', sa.Integer(), nullable=False),
    sa.Column('temp_coins_multiplier', sa.Float(), nullable=True),
    sa.Column('bonus_access_roles_ids', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=False),
    sa.Column('level_roles', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=False),
    sa.Column('count_messages_type', sa.String(), server_default=sa.text("'channel_only'"), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_table('guildloggingconfig',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('bans_log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('clans_log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('members_log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('messages_log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('voices_log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('moderation_log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('tickets_log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('roles_log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('channels_log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('reactions_log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('private_rooms_log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('economy_log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('message_log_ignoring_channels_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_table('guildmoderationconfig',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('moderation_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('leadership_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('count_moderator_messages_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('ban_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('mute_score', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('ban_score', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('kick_score', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('ticket_score', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('role_request_score', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('role_remove_score', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('ticket_ban_score', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('mpmute_score', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('vmute_score', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('message_score', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('trackable_moderation_role_id', sa.BigInteger(), nullable=True),
    sa.Column('ban_request_ping_role_id', sa.BigInteger(), nullable=True),
    sa.Column('send_ban_request_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('mpmute_role_id', sa.BigInteger(), nullable=True),
    sa.Column('vmute_role_id', sa.BigInteger(), nullable=True),
    sa.Column('mute_role_id', sa.BigInteger(), nullable=True),
    sa.Column('mute_type', sa.String(), nullable=False),
    sa.Column('fraction_roles_access_roles_ids', sa.JSON(), nullable=False),
    sa.Column('leader_access_rr_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_table('guildnotificationsconfig',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('notifications_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('notifications_for_moderation_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('notifications_from_bot_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_table('guildprivatechannelsconfig',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('private_rooms_create_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_table('guildticketsconfig',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('tickets_count', sa.Integer(), nullable=False),
    sa.Column('new_tickets_category_id', sa.BigInteger(), nullable=True),
    sa.Column('closed_tickets_category_id', sa.BigInteger(), nullable=True),
    sa.Column('create_ticket_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('pinned_tickets_category_id', sa.BigInteger(), nullable=True),
    sa.Column('create_ticket_ping_role_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_table('mainguildconfig',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('rules_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('create_proposal_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('proposals_count', sa.Integer(), nullable=False),
    sa.Column('illegal_roles', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=False),
    sa.Column('organizational_roles', sa.JSON(), nullable=False),
    sa.Column('voice_temp_roles', sa.JSON(), nullable=False),
    sa.Column('faq', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('check_role_requests_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('guild_rules', sa.JSON(), server_default=sa.text('\'{"chapters": []}\'::json'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_table('moderationmessage',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('moderator_id', sa.BigInteger(), nullable=False),
    sa.Column('time_now', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_moderationmessages_guild_id_moderator_id_time_now', 'moderationmessage', ['guild_id', 'moderator_id', 'time_now'], unique=False)
    op.create_table('notifystate',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('moderator_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.Enum('pending', 'timed_out', name='notifystateenum', native_enum=False), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notify_guild_user_end_time_desc', 'notifystate', ['guild_id', 'user_id', sa.literal_column('end_time DESC')], unique=False)
    op.create_table('privateroomstate',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('punish',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('moderator_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('original_duration', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_now', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_punish_guild_user_time_now', 'punish', ['guild_id', 'user_id', 'time_now'], unique=False)
    op.create_table('rolerequeststate',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=True),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('moderator_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.Enum('pending', 'approved', 'denied', 'canceled', 'expired', 'removed', name='rolerequeststateenum', native_enum=False), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rr_author_updated_desc', 'rolerequeststate', ['author_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_index('idx_rr_guild_author_updated_desc', 'rolerequeststate', ['guild_id', 'author_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('shoporderstate',
    sa.Column('custom_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.Enum('pending', 'approved', 'denied', name='shoporderstateenum', native_enum=False), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_id')
    )
    op.create_table('tempeconomymultiplier',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('multiplier_type', sa.Enum('exp', 'coins', name='multipliertypeenum', native_enum=False), nullable=False),
    sa.Column('multiplier', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'multiplier_type', name='ux_temp_multiplier_guild_type')
    )
    op.create_index('ix_temp_economy_multipliers_end_time', 'tempeconomymultiplier', ['end_time'], unique=False)
    op.create_index('ix_temp_economy_multipliers_guild_type_end_time', 'tempeconomymultiplier', ['guild_id', 'multiplier_type'], unique=False)
    op.create_table('temppunish',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_temp_punish_guild_user_time_now', 'temppunish', ['guild_id', 'user_id', 'end_time'], unique=False)
    op.create_table('temprole',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_temp_role_guild_user_time_now', 'temprole', ['guild_id', 'user_id', 'role_id', 'end_time'], unique=False)
    op.create_table('ticketstate',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('moderator_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('state', sa.Enum('opened', 'pinned', 'closed', 'deleted', name='ticketstateenum', native_enum=False), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ticket_guild_author_updated_desc', 'ticketstate', ['guild_id', 'author_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('transferhistory',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('receiver_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('messages_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('current_exp', sa.Integer(), nullable=False),
    sa.Column('exp_to_level', sa.Integer(), nullable=False),
    sa.Column('voice_activity', sa.BigInteger(), nullable=False),
    sa.Column('temp_voice_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reward_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ticket_ban', sa.Boolean(), nullable=False),
    sa.Column('role_request_ban', sa.Boolean(), nullable=False),
    sa.Column('battle_pass_level', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('battle_pass_points', sa.Integer(), nullable=False),
    sa.Column('inventory', sa.JSON(), server_default=sa.text('\'{"cases": {}, "colors": []}\'::json'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'user_id', name='ux_user_guild_user')
    )
    op.create_table('clanmember',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('clan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('leader', 'deputy', 'member', name='clanmemberroleenum', native_enum=False), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['clan_id'], ['clan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'user_id', name='uq_member_guild_user')
    )
    op.create_index('ix_clan_members_clan_role', 'clanmember', ['clan_id', 'role'], unique=False)
    op.create_index(op.f('ix_clanmember_clan_id'), 'clanmember', ['clan_id'], unique=False)
    op.create_index(op.f('ix_clanmember_guild_id'), 'clanmember', ['guild_id'], unique=False)
    op.create_index(op.f('ix_clanmember_user_id'), 'clanmember', ['user_id'], unique=False)
    op.create_index('uq_one_leader_per_clan', 'clanmember', ['clan_id'], unique=True, postgresql_where=sa.text("role = 'leader'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_one_leader_per_clan', table_name='clanmember', postgresql_where=sa.text("role = 'leader'"))
    op.drop_index(op.f('ix_clanmember_user_id'), table_name='clanmember')
    op.drop_index(op.f('ix_clanmember_guild_id'), table_name='clanmember')
    op.drop_index(op.f('ix_clanmember_clan_id'), table_name='clanmember')
    op.drop_index('ix_clan_members_clan_role', table_name='clanmember')
    op.drop_table('clanmember')
    op.drop_table('user')
    op.drop_table('transferhistory')
    op.drop_index('idx_ticket_guild_author_updated_desc', table_name='ticketstate')
    op.drop_table('ticketstate')
    op.drop_index('ix_temp_role_guild_user_time_now', table_name='temprole')
    op.drop_table('temprole')
    op.drop_index('ix_temp_punish_guild_user_time_now', table_name='temppunish')
    op.drop_table('temppunish')
    op.drop_index('ix_temp_economy_multipliers_guild_type_end_time', table_name='tempeconomymultiplier')
    op.drop_index('ix_temp_economy_multipliers_end_time', table_name='tempeconomymultiplier')
    op.drop_table('tempeconomymultiplier')
    op.drop_table('shoporderstate')
    op.drop_index('idx_rr_guild_author_updated_desc', table_name='rolerequeststate')
    op.drop_index('idx_rr_author_updated_desc', table_name='rolerequeststate')
    op.drop_table('rolerequeststate')
    op.drop_index('ix_punish_guild_user_time_now', table_name='punish')
    op.drop_table('punish')
    op.drop_table('privateroomstate')
    op.drop_index('idx_notify_guild_user_end_time_desc', table_name='notifystate')
    op.drop_table('notifystate')
    op.drop_index('ix_moderationmessages_guild_id_moderator_id_time_now', table_name='moderationmessage')
    op.drop_table('moderationmessage')
    op.drop_table('mainguildconfig')
    op.drop_table('guildticketsconfig')
    op.drop_table('guildprivatechannelsconfig')
    op.drop_table('guildnotificationsconfig')
    op.drop_table('guildmoderationconfig')
    op.drop_table('guildloggingconfig')
    op.drop_table('guildlevelsconfig')
    op.drop_table('guildinfomakerconfig')
    op.drop_table('guildeconomyconfig')
    op.drop_table('guildclansconfig')
    op.drop_index(op.f('ix_clan_guild_id'), table_name='clan')
    op.drop_table('clan')
    op.drop_index('ix_changestats_guild_id_moderator_id_time_now', table_name='changestat')
    op.drop_table('changestat')
    # ### end Alembic commands ###
