"""Fri Sep 26 10:22:45 PM CEST 2025

Revision ID: d676c79bfe45
Revises: cd80e7f34815
Create Date: 2025-09-26 22:22:50.870226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd676c79bfe45'
down_revision: Union[str, Sequence[str], None] = 'cd80e7f34815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rolerequeststate', sa.Column('channel_id', sa.BigInteger(), nullable=True))
    op.add_column('rolerequeststate', sa.Column('role_id', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rolerequeststate', 'channel_id')
    # ### end Alembic commands ###
