"""Mon Oct 20 09:56:09 PM CEST 2025

Revision ID: db6382b98881
Revises: 26db324cb473
Create Date: 2025-10-20 21:56:11.032485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db6382b98881'
down_revision: Union[str, Sequence[str], None] = '26db324cb473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_clan_member'), 'clanmember', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_clan_member'), 'clanmember', ['clan_id', 'user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
