"""Fri Oct 31 06:10:09 PM CET 2025

Revision ID: e3b3c25bc7e5
Revises: 4b32380ab165
Create Date: 2025-10-31 18:10:15.135215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3b3c25bc7e5'
down_revision: Union[str, Sequence[str], None] = '4b32380ab165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guildeconomyconfig', sa.Column('last_roulette_games', sa.ARRAY(sa.String()), server_default=sa.text("'{}'::text[]"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guildeconomyconfig', 'last_roulette_games')
    # ### end Alembic commands ###
