"""add guildmetaconfig model

Revision ID: f19803671fa4
Revises: d5bfd240d0dd
Create Date: 2025-12-15 18:39:39.172364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f19803671fa4'
down_revision: Union[str, Sequence[str], None] = 'd5bfd240d0dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guildmetaconfig',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('other_config_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('logging_config_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('economy_config_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('levels_config_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('clans_config_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('private_channels_config_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('moderation_config_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('notifications_config_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('infomaker_config_access_roles_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guildmetaconfig')
    # ### end Alembic commands ###
