"""Wed Nov  5 06:11:38 PM CET 2025

Revision ID: f52ae9082436
Revises: 784ae334b2f8
Create Date: 2025-11-05 18:11:45.738095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f52ae9082436'
down_revision: Union[str, Sequence[str], None] = '784ae334b2f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temprole',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_temp_role_guild_user_time_now', 'temprole', ['guild_id', 'user_id', 'role_id', 'end_time'], unique=False)
    op.alter_column('clan', 'coins',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('rolerequeststate', 'state',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('pending', 'approved', 'denied', 'canceled', 'expired', name='rolerequeststateenum', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rolerequeststate', 'state',
               existing_type=sa.Enum('pending', 'approved', 'denied', 'canceled', 'expired', name='rolerequeststateenum', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    op.alter_column('clan', 'coins',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_index('ix_temp_role_guild_user_time_now', table_name='temprole')
    op.drop_table('temprole')
    # ### end Alembic commands ###
