"""Tue Oct 28 06:40:59 PM CET 2025

Revision ID: f98e57314a4b
Revises: d9955f3a91ef
Create Date: 2025-10-28 18:41:05.612262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f98e57314a4b'
down_revision: Union[str, Sequence[str], None] = 'd9955f3a91ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guildclansconfig', sa.Column('clan_reputation_per_message', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.alter_column('guildclansconfig', 'clan_reputation_per_payday',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guildclansconfig', 'clan_reputation_per_payday',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('guildclansconfig', 'clan_reputation_per_message')
    # ### end Alembic commands ###
