PERMISSION_NAME_MAP = [
    ("create_instant_invite", "Create Invites"),
    ("kick_members", "Kick Members"),
    ("ban_members", "Ban Members"),
    ("administrator", "Administrator"),
    ("manage_channels", "Manage Channels"),
    ("manage_guild", "Manage Server"),
    ("add_reactions", "Add Reactions"),
    ("view_audit_log", "View Audit Log"),
    ("view_channel", "View Channel"),
    ("send_messages", "Send Messages"),
    ("send_tts_messages", "Send TTS Messages"),
    ("manage_messages", "Manage Messages"),
    ("embed_links", "Embed Links"),
    ("attach_files", "Attach Files"),
    ("read_message_history", "Read Message History"),
    ("mention_everyone", "Mention Everyone"),
    ("use_external_emojis", "Use External Emojis"),
    ("view_guild_insights", "View Server Insights"),
    ("connect", "Connect (Voice)"),
    ("speak", "Speak (Voice)"),
    ("mute_members", "Mute Members"),
    ("deafen_members", "Deafen Members"),
    ("move_members", "Move Members"),
    ("use_voice_activation", "Use Voice Activity"),
    ("change_nickname", "Change Nickname"),
    ("manage_nicknames", "Manage Nicknames"),
    ("manage_roles", "Manage Roles"),
    ("manage_webhooks", "Manage Webhooks"),
    ("manage_expressions", "Manage Expressions"),
    ("use_application_commands", "Use Application Commands"),
    ("request_to_speak", "Request to Speak"),
    ("manage_events", "Manage Events"),
    ("manage_threads", "Manage Threads"),
    ("create_public_threads", "Create Public Threads"),
    ("create_private_threads", "Create Private Threads"),
    ("use_external_stickers", "Use External Stickers"),
    ("send_messages_in_threads", "Send Messages in Threads"),
    ("use_embedded_activities", "Use Embedded Activities"),
    ("moderate_members", "Moderate Members"),
    ("use_soundboard", "Use Soundboard"),
    ("create_expressions", "Create Expressions"),
    ("create_events", "Create Events"),
    ("use_external_sounds", "Use External Sounds"),
    ("send_voice_messages", "Send Voice Messages"),
    ("send_polls", "Send Polls"),
    ("use_external_apps", "Use External Apps"),
    ("stream", "Stream Video"),
    ("priority_speaker", "Priority Speaker"),
]
